Backend: Vitis
ClockPeriod: 5
ClockUncertainty: 27%
HLSConfig:
  LayerName:
    flatten:
      Trace: false
    input_layer:
      Trace: false
    max_pooling2d:
      ConvImplementation: LineBuffer
      ReuseFactor: 1
      Trace: false
    q_conv2d:
      ConvImplementation: LineBuffer
      ParallelizationFactor: 1
      ReuseFactor: 1
      Trace: false
    q_conv2d_iq:
      Trace: false
    q_conv2d_relu:
      ReuseFactor: 1
      TableSize: 1024
      Trace: false
    q_dense:
      ReuseFactor: 1
      Trace: false
    q_dense_iq:
      Trace: false
    reshape:
      Trace: false
  Model:
    BitExact: null
    BramFactor: 1000000000
    Precision:
      default: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
InputShapes:
  input_layer:
  - 256
  - 4
KerasModel: !keras_model 'cnn_core_project/keras_model.keras'
OutputDir: cnn_core_project
OutputPredictions: null
OutputShapes:
  layer9_out:
  - 1
Part: xcku5p-ffvb676-2-e
ProjectName: cnn_core
Stamp: d797458e
Version: 1.0.0
WriterConfig:
  Namespace: null
  TBOutputStream: both
  WriteEmulationConstants: false
  WriteTar: false
  WriteWeightsTxt: true
