-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_core_relu_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_28u_relu_config4_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer3x4_out_dout : IN STD_LOGIC_VECTOR (251 downto 0);
    layer3x4_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    layer3x4_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    layer3x4_out_empty_n : IN STD_LOGIC;
    layer3x4_out_read : OUT STD_LOGIC;
    layer4x4_out_din : OUT STD_LOGIC_VECTOR (447 downto 0);
    layer4x4_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    layer4x4_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    layer4x4_out_full_n : IN STD_LOGIC;
    layer4x4_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of cnn_core_relu_array_ap_fixed_28u_array_ap_fixed_16_6_5_3_0_28u_relu_config4_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv7_54 : STD_LOGIC_VECTOR (6 downto 0) := "1010100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv32_1A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011010";
    constant ap_const_lv32_1B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011011";
    constant ap_const_lv32_23 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100011";
    constant ap_const_lv32_24 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100100";
    constant ap_const_lv32_2C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101100";
    constant ap_const_lv32_2D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101101";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_3E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111110";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_47 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000111";
    constant ap_const_lv32_48 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001000";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_51 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010001";
    constant ap_const_lv32_59 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011001";
    constant ap_const_lv32_5A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011010";
    constant ap_const_lv32_62 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100010";
    constant ap_const_lv32_63 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100011";
    constant ap_const_lv32_6B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101011";
    constant ap_const_lv32_6C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101100";
    constant ap_const_lv32_74 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110100";
    constant ap_const_lv32_75 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110101";
    constant ap_const_lv32_7D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111101";
    constant ap_const_lv32_7E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111110";
    constant ap_const_lv32_86 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000110";
    constant ap_const_lv32_87 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000111";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_98 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011000";
    constant ap_const_lv32_99 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011001";
    constant ap_const_lv32_A1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100001";
    constant ap_const_lv32_A2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100010";
    constant ap_const_lv32_AA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101010";
    constant ap_const_lv32_AB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101011";
    constant ap_const_lv32_B3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110011";
    constant ap_const_lv32_B4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110100";
    constant ap_const_lv32_BC : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111100";
    constant ap_const_lv32_BD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111101";
    constant ap_const_lv32_C5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000101";
    constant ap_const_lv32_C6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000110";
    constant ap_const_lv32_CE : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001110";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010111";
    constant ap_const_lv32_D8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011000";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_E1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100001";
    constant ap_const_lv32_E9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101001";
    constant ap_const_lv32_EA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101010";
    constant ap_const_lv32_F2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110010";
    constant ap_const_lv32_F3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110011";
    constant ap_const_lv32_FB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111011";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv32_22 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100010";
    constant ap_const_lv32_2B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101011";
    constant ap_const_lv32_34 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110100";
    constant ap_const_lv32_3D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111101";
    constant ap_const_lv32_46 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000110";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_58 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011000";
    constant ap_const_lv32_61 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100001";
    constant ap_const_lv32_6A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101010";
    constant ap_const_lv32_73 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110011";
    constant ap_const_lv32_7C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111100";
    constant ap_const_lv32_85 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000101";
    constant ap_const_lv32_8E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001110";
    constant ap_const_lv32_97 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_A9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101001";
    constant ap_const_lv32_B2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110010";
    constant ap_const_lv32_BB : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111011";
    constant ap_const_lv32_C4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000100";
    constant ap_const_lv32_CD : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001101";
    constant ap_const_lv32_D6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010110";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101000";
    constant ap_const_lv32_F1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110001";
    constant ap_const_lv32_FA : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111010";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv14_0 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000000";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln41_fu_237_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer3x4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer4x4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln51_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_reg_1546 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln52_fu_534_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln52_reg_1551 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_1_fu_538_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_1_reg_1556 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_reg_1561 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_2_fu_554_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_2_reg_1566 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_reg_1571 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_3_fu_570_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_3_reg_1576 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_1581 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_4_fu_586_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_4_reg_1586 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_1591 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_5_fu_602_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_5_reg_1596 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_1601 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_6_fu_618_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_6_reg_1606 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_1611 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_7_fu_634_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_7_reg_1616 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_1621 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_8_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_8_reg_1626 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_8_reg_1631 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_9_fu_666_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_9_reg_1636 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_1641 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_10_fu_682_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_10_reg_1646 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_s_reg_1651 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_11_fu_698_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_11_reg_1656 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_10_reg_1661 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_12_fu_714_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_12_reg_1666 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_11_reg_1671 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_13_fu_730_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_13_reg_1676 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_12_reg_1681 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_14_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_14_reg_1686 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_13_reg_1691 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_15_fu_762_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_15_reg_1696 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_14_reg_1701 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_16_fu_778_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_16_reg_1706 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_15_reg_1711 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_17_fu_794_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_17_reg_1716 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_16_reg_1721 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_18_fu_810_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_18_reg_1726 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_17_reg_1731 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_19_fu_826_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_19_reg_1736 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_reg_1741 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_20_fu_842_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_20_reg_1746 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_19_reg_1751 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_21_fu_858_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_21_reg_1756 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_20_reg_1761 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_22_fu_874_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_22_reg_1766 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_21_reg_1771 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_23_fu_890_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_23_reg_1776 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_22_reg_1781 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_24_fu_906_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_24_reg_1786 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_reg_1791 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_25_fu_922_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_25_reg_1796 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_24_reg_1801 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_26_fu_938_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_26_reg_1806 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_25_reg_1811 : STD_LOGIC_VECTOR (7 downto 0);
    signal icmp_ln51_27_fu_954_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln51_27_reg_1816 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_26_reg_1821 : STD_LOGIC_VECTOR (7 downto 0);
    signal i_fu_212 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal i_4_fu_243_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_3 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal trunc_ln44_fu_254_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_1_fu_258_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_2_fu_268_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_3_fu_278_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_4_fu_288_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_5_fu_298_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_6_fu_308_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_7_fu_318_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_8_fu_328_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_9_fu_338_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_s_fu_348_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_10_fu_358_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_11_fu_368_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_12_fu_378_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_13_fu_388_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_14_fu_398_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_15_fu_408_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_16_fu_418_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_17_fu_428_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_18_fu_438_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_19_fu_448_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_20_fu_458_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_21_fu_468_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_22_fu_478_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_23_fu_488_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_24_fu_498_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_25_fu_508_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln44_26_fu_518_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_data_fu_970_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal out_data_1_fu_977_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal out_data_2_fu_988_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal out_data_3_fu_995_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal out_data_4_fu_1006_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal out_data_5_fu_1013_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal out_data_6_fu_1024_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal out_data_7_fu_1031_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln_fu_1042_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_fu_1049_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_1_fu_1060_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_1_fu_1067_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_2_fu_1078_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_2_fu_1085_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_3_fu_1096_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_3_fu_1103_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_4_fu_1114_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_4_fu_1121_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_5_fu_1132_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_5_fu_1139_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_6_fu_1150_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_6_fu_1157_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_7_fu_1168_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_7_fu_1175_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_8_fu_1186_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_8_fu_1193_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_9_fu_1204_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_9_fu_1211_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_s_fu_1222_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_10_fu_1229_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_10_fu_1240_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_11_fu_1247_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_11_fu_1258_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_12_fu_1265_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_12_fu_1276_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_13_fu_1283_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_13_fu_1294_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_14_fu_1301_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_14_fu_1312_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_15_fu_1319_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_15_fu_1330_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_16_fu_1337_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_16_fu_1348_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_17_fu_1355_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_17_fu_1366_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_18_fu_1373_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_18_fu_1384_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_19_fu_1391_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_19_fu_1402_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_20_fu_1409_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_20_fu_1420_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_21_fu_1427_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_21_fu_1438_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_22_fu_1445_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal shl_ln52_22_fu_1456_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal select_ln51_23_fu_1463_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal zext_ln51_22_fu_1452_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_21_fu_1434_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_20_fu_1416_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_19_fu_1398_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_18_fu_1380_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_17_fu_1362_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_16_fu_1344_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_15_fu_1326_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_14_fu_1308_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_13_fu_1290_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_12_fu_1272_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_11_fu_1254_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_10_fu_1236_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_9_fu_1218_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_8_fu_1200_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_7_fu_1182_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_6_fu_1164_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_5_fu_1146_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_4_fu_1128_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_3_fu_1110_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_2_fu_1092_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_1_fu_1074_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln51_fu_1056_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_3_fu_1038_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_2_fu_1020_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_1_fu_1002_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_fu_984_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal or_ln57_s_fu_1470_p29 : STD_LOGIC_VECTOR (445 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_225 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_core_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component cnn_core_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_fu_212_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_225)) then
                if ((icmp_ln41_fu_237_p2 = ap_const_lv1_0)) then 
                    i_fu_212 <= i_4_fu_243_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_212 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                icmp_ln51_10_reg_1646 <= icmp_ln51_10_fu_682_p2;
                icmp_ln51_11_reg_1656 <= icmp_ln51_11_fu_698_p2;
                icmp_ln51_12_reg_1666 <= icmp_ln51_12_fu_714_p2;
                icmp_ln51_13_reg_1676 <= icmp_ln51_13_fu_730_p2;
                icmp_ln51_14_reg_1686 <= icmp_ln51_14_fu_746_p2;
                icmp_ln51_15_reg_1696 <= icmp_ln51_15_fu_762_p2;
                icmp_ln51_16_reg_1706 <= icmp_ln51_16_fu_778_p2;
                icmp_ln51_17_reg_1716 <= icmp_ln51_17_fu_794_p2;
                icmp_ln51_18_reg_1726 <= icmp_ln51_18_fu_810_p2;
                icmp_ln51_19_reg_1736 <= icmp_ln51_19_fu_826_p2;
                icmp_ln51_1_reg_1556 <= icmp_ln51_1_fu_538_p2;
                icmp_ln51_20_reg_1746 <= icmp_ln51_20_fu_842_p2;
                icmp_ln51_21_reg_1756 <= icmp_ln51_21_fu_858_p2;
                icmp_ln51_22_reg_1766 <= icmp_ln51_22_fu_874_p2;
                icmp_ln51_23_reg_1776 <= icmp_ln51_23_fu_890_p2;
                icmp_ln51_24_reg_1786 <= icmp_ln51_24_fu_906_p2;
                icmp_ln51_25_reg_1796 <= icmp_ln51_25_fu_922_p2;
                icmp_ln51_26_reg_1806 <= icmp_ln51_26_fu_938_p2;
                icmp_ln51_27_reg_1816 <= icmp_ln51_27_fu_954_p2;
                icmp_ln51_2_reg_1566 <= icmp_ln51_2_fu_554_p2;
                icmp_ln51_3_reg_1576 <= icmp_ln51_3_fu_570_p2;
                icmp_ln51_4_reg_1586 <= icmp_ln51_4_fu_586_p2;
                icmp_ln51_5_reg_1596 <= icmp_ln51_5_fu_602_p2;
                icmp_ln51_6_reg_1606 <= icmp_ln51_6_fu_618_p2;
                icmp_ln51_7_reg_1616 <= icmp_ln51_7_fu_634_p2;
                icmp_ln51_8_reg_1626 <= icmp_ln51_8_fu_650_p2;
                icmp_ln51_9_reg_1636 <= icmp_ln51_9_fu_666_p2;
                icmp_ln51_reg_1546 <= icmp_ln51_fu_528_p2;
                tmp_10_reg_1661 <= layer3x4_out_dout(106 downto 99);
                tmp_11_reg_1671 <= layer3x4_out_dout(115 downto 108);
                tmp_12_reg_1681 <= layer3x4_out_dout(124 downto 117);
                tmp_13_reg_1691 <= layer3x4_out_dout(133 downto 126);
                tmp_14_reg_1701 <= layer3x4_out_dout(142 downto 135);
                tmp_15_reg_1711 <= layer3x4_out_dout(151 downto 144);
                tmp_16_reg_1721 <= layer3x4_out_dout(160 downto 153);
                tmp_17_reg_1731 <= layer3x4_out_dout(169 downto 162);
                tmp_18_reg_1741 <= layer3x4_out_dout(178 downto 171);
                tmp_19_reg_1751 <= layer3x4_out_dout(187 downto 180);
                tmp_1_reg_1561 <= layer3x4_out_dout(16 downto 9);
                tmp_20_reg_1761 <= layer3x4_out_dout(196 downto 189);
                tmp_21_reg_1771 <= layer3x4_out_dout(205 downto 198);
                tmp_22_reg_1781 <= layer3x4_out_dout(214 downto 207);
                tmp_23_reg_1791 <= layer3x4_out_dout(223 downto 216);
                tmp_24_reg_1801 <= layer3x4_out_dout(232 downto 225);
                tmp_25_reg_1811 <= layer3x4_out_dout(241 downto 234);
                tmp_26_reg_1821 <= layer3x4_out_dout(250 downto 243);
                tmp_2_reg_1571 <= layer3x4_out_dout(25 downto 18);
                tmp_3_reg_1581 <= layer3x4_out_dout(34 downto 27);
                tmp_4_reg_1591 <= layer3x4_out_dout(43 downto 36);
                tmp_5_reg_1601 <= layer3x4_out_dout(52 downto 45);
                tmp_6_reg_1611 <= layer3x4_out_dout(61 downto 54);
                tmp_7_reg_1621 <= layer3x4_out_dout(70 downto 63);
                tmp_8_reg_1631 <= layer3x4_out_dout(79 downto 72);
                tmp_9_reg_1641 <= layer3x4_out_dout(88 downto 81);
                tmp_s_reg_1651 <= layer3x4_out_dout(97 downto 90);
                trunc_ln52_reg_1551 <= trunc_ln52_fu_534_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer3x4_out_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer3x4_out_empty_n = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(layer4x4_out_full_n)
    begin
                ap_block_state3_pp0_stage0_iter2 <= (layer4x4_out_full_n = ap_const_logic_0);
    end process;


    ap_condition_225_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_225 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln41_fu_237_p2, ap_start_int)
    begin
        if (((icmp_ln41_fu_237_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_start_int = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_3_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_212, ap_loop_init, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_3 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_3 <= i_fu_212;
        end if; 
    end process;

    i_4_fu_243_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_3) + unsigned(ap_const_lv7_1));
    icmp_ln41_fu_237_p2 <= "1" when (ap_sig_allocacmp_i_3 = ap_const_lv7_54) else "0";
    icmp_ln51_10_fu_682_p2 <= "1" when (signed(trunc_ln44_s_fu_348_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_11_fu_698_p2 <= "1" when (signed(trunc_ln44_10_fu_358_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_12_fu_714_p2 <= "1" when (signed(trunc_ln44_11_fu_368_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_13_fu_730_p2 <= "1" when (signed(trunc_ln44_12_fu_378_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_14_fu_746_p2 <= "1" when (signed(trunc_ln44_13_fu_388_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_15_fu_762_p2 <= "1" when (signed(trunc_ln44_14_fu_398_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_16_fu_778_p2 <= "1" when (signed(trunc_ln44_15_fu_408_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_17_fu_794_p2 <= "1" when (signed(trunc_ln44_16_fu_418_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_18_fu_810_p2 <= "1" when (signed(trunc_ln44_17_fu_428_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_19_fu_826_p2 <= "1" when (signed(trunc_ln44_18_fu_438_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_1_fu_538_p2 <= "1" when (signed(trunc_ln44_1_fu_258_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_20_fu_842_p2 <= "1" when (signed(trunc_ln44_19_fu_448_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_21_fu_858_p2 <= "1" when (signed(trunc_ln44_20_fu_458_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_22_fu_874_p2 <= "1" when (signed(trunc_ln44_21_fu_468_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_23_fu_890_p2 <= "1" when (signed(trunc_ln44_22_fu_478_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_24_fu_906_p2 <= "1" when (signed(trunc_ln44_23_fu_488_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_25_fu_922_p2 <= "1" when (signed(trunc_ln44_24_fu_498_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_26_fu_938_p2 <= "1" when (signed(trunc_ln44_25_fu_508_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_27_fu_954_p2 <= "1" when (signed(trunc_ln44_26_fu_518_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_2_fu_554_p2 <= "1" when (signed(trunc_ln44_2_fu_268_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_3_fu_570_p2 <= "1" when (signed(trunc_ln44_3_fu_278_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_4_fu_586_p2 <= "1" when (signed(trunc_ln44_4_fu_288_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_5_fu_602_p2 <= "1" when (signed(trunc_ln44_5_fu_298_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_6_fu_618_p2 <= "1" when (signed(trunc_ln44_6_fu_308_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_7_fu_634_p2 <= "1" when (signed(trunc_ln44_7_fu_318_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_8_fu_650_p2 <= "1" when (signed(trunc_ln44_8_fu_328_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_9_fu_666_p2 <= "1" when (signed(trunc_ln44_9_fu_338_p4) > signed(ap_const_lv9_0)) else "0";
    icmp_ln51_fu_528_p2 <= "1" when (signed(trunc_ln44_fu_254_p1) > signed(ap_const_lv9_0)) else "0";

    layer3x4_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer3x4_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer3x4_out_blk_n <= layer3x4_out_empty_n;
        else 
            layer3x4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer3x4_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer3x4_out_read <= ap_const_logic_1;
        else 
            layer3x4_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer4x4_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, layer4x4_out_full_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            layer4x4_out_blk_n <= layer4x4_out_full_n;
        else 
            layer4x4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer4x4_out_din <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln57_s_fu_1470_p29),448));

    layer4x4_out_write_assign_proc : process(ap_enable_reg_pp0_iter2, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            layer4x4_out_write <= ap_const_logic_1;
        else 
            layer4x4_out_write <= ap_const_logic_0;
        end if; 
    end process;

    or_ln57_s_fu_1470_p29 <= (((((((((((((((((((((((((((select_ln51_23_fu_1463_p3 & zext_ln51_22_fu_1452_p1) & zext_ln51_21_fu_1434_p1) & zext_ln51_20_fu_1416_p1) & zext_ln51_19_fu_1398_p1) & zext_ln51_18_fu_1380_p1) & zext_ln51_17_fu_1362_p1) & zext_ln51_16_fu_1344_p1) & zext_ln51_15_fu_1326_p1) & zext_ln51_14_fu_1308_p1) & zext_ln51_13_fu_1290_p1) & zext_ln51_12_fu_1272_p1) & zext_ln51_11_fu_1254_p1) & zext_ln51_10_fu_1236_p1) & zext_ln51_9_fu_1218_p1) & zext_ln51_8_fu_1200_p1) & zext_ln51_7_fu_1182_p1) & zext_ln51_6_fu_1164_p1) & zext_ln51_5_fu_1146_p1) & zext_ln51_4_fu_1128_p1) & zext_ln51_3_fu_1110_p1) & zext_ln51_2_fu_1092_p1) & zext_ln51_1_fu_1074_p1) & zext_ln51_fu_1056_p1) & zext_ln45_3_fu_1038_p1) & zext_ln45_2_fu_1020_p1) & zext_ln45_1_fu_1002_p1) & zext_ln45_fu_984_p1);
    out_data_1_fu_977_p3 <= 
        out_data_fu_970_p3 when (icmp_ln51_reg_1546(0) = '1') else 
        ap_const_lv14_0;
    out_data_2_fu_988_p3 <= (tmp_1_reg_1561 & ap_const_lv6_0);
    out_data_3_fu_995_p3 <= 
        out_data_2_fu_988_p3 when (icmp_ln51_1_reg_1556(0) = '1') else 
        ap_const_lv14_0;
    out_data_4_fu_1006_p3 <= (tmp_2_reg_1571 & ap_const_lv6_0);
    out_data_5_fu_1013_p3 <= 
        out_data_4_fu_1006_p3 when (icmp_ln51_2_reg_1566(0) = '1') else 
        ap_const_lv14_0;
    out_data_6_fu_1024_p3 <= (tmp_3_reg_1581 & ap_const_lv6_0);
    out_data_7_fu_1031_p3 <= 
        out_data_6_fu_1024_p3 when (icmp_ln51_3_reg_1576(0) = '1') else 
        ap_const_lv14_0;
    out_data_fu_970_p3 <= (trunc_ln52_reg_1551 & ap_const_lv6_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln51_10_fu_1229_p3 <= 
        shl_ln52_s_fu_1222_p3 when (icmp_ln51_14_reg_1686(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_11_fu_1247_p3 <= 
        shl_ln52_10_fu_1240_p3 when (icmp_ln51_15_reg_1696(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_12_fu_1265_p3 <= 
        shl_ln52_11_fu_1258_p3 when (icmp_ln51_16_reg_1706(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_13_fu_1283_p3 <= 
        shl_ln52_12_fu_1276_p3 when (icmp_ln51_17_reg_1716(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_14_fu_1301_p3 <= 
        shl_ln52_13_fu_1294_p3 when (icmp_ln51_18_reg_1726(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_15_fu_1319_p3 <= 
        shl_ln52_14_fu_1312_p3 when (icmp_ln51_19_reg_1736(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_16_fu_1337_p3 <= 
        shl_ln52_15_fu_1330_p3 when (icmp_ln51_20_reg_1746(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_17_fu_1355_p3 <= 
        shl_ln52_16_fu_1348_p3 when (icmp_ln51_21_reg_1756(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_18_fu_1373_p3 <= 
        shl_ln52_17_fu_1366_p3 when (icmp_ln51_22_reg_1766(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_19_fu_1391_p3 <= 
        shl_ln52_18_fu_1384_p3 when (icmp_ln51_23_reg_1776(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_1_fu_1067_p3 <= 
        shl_ln52_1_fu_1060_p3 when (icmp_ln51_5_reg_1596(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_20_fu_1409_p3 <= 
        shl_ln52_19_fu_1402_p3 when (icmp_ln51_24_reg_1786(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_21_fu_1427_p3 <= 
        shl_ln52_20_fu_1420_p3 when (icmp_ln51_25_reg_1796(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_22_fu_1445_p3 <= 
        shl_ln52_21_fu_1438_p3 when (icmp_ln51_26_reg_1806(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_23_fu_1463_p3 <= 
        shl_ln52_22_fu_1456_p3 when (icmp_ln51_27_reg_1816(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_2_fu_1085_p3 <= 
        shl_ln52_2_fu_1078_p3 when (icmp_ln51_6_reg_1606(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_3_fu_1103_p3 <= 
        shl_ln52_3_fu_1096_p3 when (icmp_ln51_7_reg_1616(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_4_fu_1121_p3 <= 
        shl_ln52_4_fu_1114_p3 when (icmp_ln51_8_reg_1626(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_5_fu_1139_p3 <= 
        shl_ln52_5_fu_1132_p3 when (icmp_ln51_9_reg_1636(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_6_fu_1157_p3 <= 
        shl_ln52_6_fu_1150_p3 when (icmp_ln51_10_reg_1646(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_7_fu_1175_p3 <= 
        shl_ln52_7_fu_1168_p3 when (icmp_ln51_11_reg_1656(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_8_fu_1193_p3 <= 
        shl_ln52_8_fu_1186_p3 when (icmp_ln51_12_reg_1666(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_9_fu_1211_p3 <= 
        shl_ln52_9_fu_1204_p3 when (icmp_ln51_13_reg_1676(0) = '1') else 
        ap_const_lv14_0;
    select_ln51_fu_1049_p3 <= 
        shl_ln_fu_1042_p3 when (icmp_ln51_4_reg_1586(0) = '1') else 
        ap_const_lv14_0;
    shl_ln52_10_fu_1240_p3 <= (tmp_14_reg_1701 & ap_const_lv6_0);
    shl_ln52_11_fu_1258_p3 <= (tmp_15_reg_1711 & ap_const_lv6_0);
    shl_ln52_12_fu_1276_p3 <= (tmp_16_reg_1721 & ap_const_lv6_0);
    shl_ln52_13_fu_1294_p3 <= (tmp_17_reg_1731 & ap_const_lv6_0);
    shl_ln52_14_fu_1312_p3 <= (tmp_18_reg_1741 & ap_const_lv6_0);
    shl_ln52_15_fu_1330_p3 <= (tmp_19_reg_1751 & ap_const_lv6_0);
    shl_ln52_16_fu_1348_p3 <= (tmp_20_reg_1761 & ap_const_lv6_0);
    shl_ln52_17_fu_1366_p3 <= (tmp_21_reg_1771 & ap_const_lv6_0);
    shl_ln52_18_fu_1384_p3 <= (tmp_22_reg_1781 & ap_const_lv6_0);
    shl_ln52_19_fu_1402_p3 <= (tmp_23_reg_1791 & ap_const_lv6_0);
    shl_ln52_1_fu_1060_p3 <= (tmp_5_reg_1601 & ap_const_lv6_0);
    shl_ln52_20_fu_1420_p3 <= (tmp_24_reg_1801 & ap_const_lv6_0);
    shl_ln52_21_fu_1438_p3 <= (tmp_25_reg_1811 & ap_const_lv6_0);
    shl_ln52_22_fu_1456_p3 <= (tmp_26_reg_1821 & ap_const_lv6_0);
    shl_ln52_2_fu_1078_p3 <= (tmp_6_reg_1611 & ap_const_lv6_0);
    shl_ln52_3_fu_1096_p3 <= (tmp_7_reg_1621 & ap_const_lv6_0);
    shl_ln52_4_fu_1114_p3 <= (tmp_8_reg_1631 & ap_const_lv6_0);
    shl_ln52_5_fu_1132_p3 <= (tmp_9_reg_1641 & ap_const_lv6_0);
    shl_ln52_6_fu_1150_p3 <= (tmp_s_reg_1651 & ap_const_lv6_0);
    shl_ln52_7_fu_1168_p3 <= (tmp_10_reg_1661 & ap_const_lv6_0);
    shl_ln52_8_fu_1186_p3 <= (tmp_11_reg_1671 & ap_const_lv6_0);
    shl_ln52_9_fu_1204_p3 <= (tmp_12_reg_1681 & ap_const_lv6_0);
    shl_ln52_s_fu_1222_p3 <= (tmp_13_reg_1691 & ap_const_lv6_0);
    shl_ln_fu_1042_p3 <= (tmp_4_reg_1591 & ap_const_lv6_0);
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln44_10_fu_358_p4 <= layer3x4_out_dout(107 downto 99);
    trunc_ln44_11_fu_368_p4 <= layer3x4_out_dout(116 downto 108);
    trunc_ln44_12_fu_378_p4 <= layer3x4_out_dout(125 downto 117);
    trunc_ln44_13_fu_388_p4 <= layer3x4_out_dout(134 downto 126);
    trunc_ln44_14_fu_398_p4 <= layer3x4_out_dout(143 downto 135);
    trunc_ln44_15_fu_408_p4 <= layer3x4_out_dout(152 downto 144);
    trunc_ln44_16_fu_418_p4 <= layer3x4_out_dout(161 downto 153);
    trunc_ln44_17_fu_428_p4 <= layer3x4_out_dout(170 downto 162);
    trunc_ln44_18_fu_438_p4 <= layer3x4_out_dout(179 downto 171);
    trunc_ln44_19_fu_448_p4 <= layer3x4_out_dout(188 downto 180);
    trunc_ln44_1_fu_258_p4 <= layer3x4_out_dout(17 downto 9);
    trunc_ln44_20_fu_458_p4 <= layer3x4_out_dout(197 downto 189);
    trunc_ln44_21_fu_468_p4 <= layer3x4_out_dout(206 downto 198);
    trunc_ln44_22_fu_478_p4 <= layer3x4_out_dout(215 downto 207);
    trunc_ln44_23_fu_488_p4 <= layer3x4_out_dout(224 downto 216);
    trunc_ln44_24_fu_498_p4 <= layer3x4_out_dout(233 downto 225);
    trunc_ln44_25_fu_508_p4 <= layer3x4_out_dout(242 downto 234);
    trunc_ln44_26_fu_518_p4 <= layer3x4_out_dout(251 downto 243);
    trunc_ln44_2_fu_268_p4 <= layer3x4_out_dout(26 downto 18);
    trunc_ln44_3_fu_278_p4 <= layer3x4_out_dout(35 downto 27);
    trunc_ln44_4_fu_288_p4 <= layer3x4_out_dout(44 downto 36);
    trunc_ln44_5_fu_298_p4 <= layer3x4_out_dout(53 downto 45);
    trunc_ln44_6_fu_308_p4 <= layer3x4_out_dout(62 downto 54);
    trunc_ln44_7_fu_318_p4 <= layer3x4_out_dout(71 downto 63);
    trunc_ln44_8_fu_328_p4 <= layer3x4_out_dout(80 downto 72);
    trunc_ln44_9_fu_338_p4 <= layer3x4_out_dout(89 downto 81);
    trunc_ln44_fu_254_p1 <= layer3x4_out_dout(9 - 1 downto 0);
    trunc_ln44_s_fu_348_p4 <= layer3x4_out_dout(98 downto 90);
    trunc_ln52_fu_534_p1 <= layer3x4_out_dout(8 - 1 downto 0);
    zext_ln45_1_fu_1002_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_3_fu_995_p3),16));
    zext_ln45_2_fu_1020_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_5_fu_1013_p3),16));
    zext_ln45_3_fu_1038_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_7_fu_1031_p3),16));
    zext_ln45_fu_984_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_data_1_fu_977_p3),16));
    zext_ln51_10_fu_1236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_10_fu_1229_p3),16));
    zext_ln51_11_fu_1254_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_11_fu_1247_p3),16));
    zext_ln51_12_fu_1272_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_12_fu_1265_p3),16));
    zext_ln51_13_fu_1290_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_13_fu_1283_p3),16));
    zext_ln51_14_fu_1308_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_14_fu_1301_p3),16));
    zext_ln51_15_fu_1326_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_15_fu_1319_p3),16));
    zext_ln51_16_fu_1344_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_16_fu_1337_p3),16));
    zext_ln51_17_fu_1362_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_17_fu_1355_p3),16));
    zext_ln51_18_fu_1380_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_18_fu_1373_p3),16));
    zext_ln51_19_fu_1398_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_19_fu_1391_p3),16));
    zext_ln51_1_fu_1074_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_1_fu_1067_p3),16));
    zext_ln51_20_fu_1416_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_20_fu_1409_p3),16));
    zext_ln51_21_fu_1434_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_21_fu_1427_p3),16));
    zext_ln51_22_fu_1452_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_22_fu_1445_p3),16));
    zext_ln51_2_fu_1092_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_2_fu_1085_p3),16));
    zext_ln51_3_fu_1110_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_3_fu_1103_p3),16));
    zext_ln51_4_fu_1128_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_4_fu_1121_p3),16));
    zext_ln51_5_fu_1146_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_5_fu_1139_p3),16));
    zext_ln51_6_fu_1164_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_6_fu_1157_p3),16));
    zext_ln51_7_fu_1182_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_7_fu_1175_p3),16));
    zext_ln51_8_fu_1200_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_8_fu_1193_p3),16));
    zext_ln51_9_fu_1218_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_9_fu_1211_p3),16));
    zext_ln51_fu_1056_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln51_fu_1049_p3),16));
end behav;
