-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_core_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s is
port (
    ap_ready : OUT STD_LOGIC;
    p_read : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read1 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read2 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read3 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read4 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read5 : IN STD_LOGIC_VECTOR (15 downto 0);
    p_read6 : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i : IN STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld : OUT STD_LOGIC;
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i : IN STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o : OUT STD_LOGIC_VECTOR (15 downto 0);
    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld : OUT STD_LOGIC;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld : OUT STD_LOGIC );
end;


architecture behav of cnn_core_shift_line_buffer_array_ap_fixed_16_6_5_3_0_7u_config6_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;


begin



    ap_ready <= ap_const_logic_1;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_assign_proc : process(p_read5, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i)
    begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o <= p_read5;
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_o_ap_vld <= ap_const_logic_1;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_assign_proc : process(p_read4, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i)
    begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o <= p_read4;
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_o_ap_vld <= ap_const_logic_1;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_assign_proc : process(p_read3, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i)
    begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o <= p_read3;
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_o_ap_vld <= ap_const_logic_1;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_assign_proc : process(p_read6, p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i)
    begin
        p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o <= p_read6;
    end process;

    p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_o_ap_vld <= ap_const_logic_1;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_assign_proc : process(p_read1, void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i)
    begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o <= p_read1;
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_o_ap_vld <= ap_const_logic_1;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_assign_proc : process(p_read, void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i)
    begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o <= p_read;
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_o_ap_vld <= ap_const_logic_1;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_i;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_3_ap_vld <= ap_const_logic_1;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_1_i;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_4_ap_vld <= ap_const_logic_1;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_2_i;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_5_ap_vld <= ap_const_logic_1;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6 <= p_ZZN4nnet22compute_pool_buffer_2dINS_5arrayI8ap_fixedILi16ELi6EL9ap_q_mode5EL9ap_3_i;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_6_ap_vld <= ap_const_logic_1;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_7_ap_vld <= ap_const_logic_1;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_1_i;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_8_ap_vld <= ap_const_logic_1;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9 <= void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_2_i;
    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_9_ap_vld <= ap_const_logic_1;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_assign_proc : process(p_read2, void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_i)
    begin
        void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o <= p_read2;
    end process;

    void_compute_pool_buffer_2d_array_const_ap_shift_reg_n_filt_stream_kernel_o_ap_vld <= ap_const_logic_1;
end behav;
