<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="17">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>cnn_core</name>
      <module_structure>Dataflow</module_structure>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>input_layer</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>input_layer</originalName>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>48</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>64</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>layer7_out</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>layer7_out</originalName>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>48</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>16</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>8</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>33</id>
              <name>layer3_out</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName>layer3_out_U</rtlName>
              <control>auto</control>
              <opType>fifo</opType>
              <implIndex>memory</implIndex>
              <coreName>FIFO</coreName>
              <isStorage>1</isStorage>
              <storageDepth>336</storageDepth>
              <coreId>78</coreId>
              <rtlModuleName>cnn_core_fifo_w63_d336_A</rtlModuleName>
            </Obj>
            <bitwidth>63</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>49</item>
          </oprand_edges>
          <opcode>alloca</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>1</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>36</id>
              <name>layer4_out</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName>layer4_out_U</rtlName>
              <control>auto</control>
              <opType>fifo</opType>
              <implIndex>memory</implIndex>
              <coreName>FIFO</coreName>
              <isStorage>1</isStorage>
              <storageDepth>336</storageDepth>
              <coreId>78</coreId>
              <rtlModuleName>cnn_core_fifo_w112_d336_A</rtlModuleName>
            </Obj>
            <bitwidth>112</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>50</item>
          </oprand_edges>
          <opcode>alloca</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>2</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>39</id>
              <name>layer5_out</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName>layer5_out_U</rtlName>
              <control>auto</control>
              <opType>fifo</opType>
              <implIndex>memory</implIndex>
              <coreName>FIFO</coreName>
              <isStorage>1</isStorage>
              <storageDepth>168</storageDepth>
              <coreId>78</coreId>
              <rtlModuleName>cnn_core_fifo_w112_d168_A</rtlModuleName>
            </Obj>
            <bitwidth>112</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>51</item>
          </oprand_edges>
          <opcode>alloca</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>3</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>42</id>
              <name>_ln43</name>
              <fileName>firmware/cnn_core.cpp</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>43</lineNumber>
              <contextFuncName>cnn_core</contextFuncName>
              <contextNormFuncName>cnn_core</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="11" tracking_level="0" version="0">
                  <first>/home/work1/Works/CNN-Core-Generator/hls_streaming</first>
                  <second class_id="12" tracking_level="0" version="0">
                    <count>1</count>
                    <item_version>0</item_version>
                    <item class_id="13" tracking_level="0" version="0">
                      <first class_id="14" tracking_level="0" version="0">
                        <first>firmware/cnn_core.cpp</first>
                        <second>cnn_core</second>
                      </first>
                      <second>43</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_U0</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>806586576</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>53</item>
            <item>54</item>
            <item>55</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>4</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>43</id>
              <name>_ln45</name>
              <fileName>firmware/cnn_core.cpp</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>45</lineNumber>
              <contextFuncName>cnn_core</contextFuncName>
              <contextNormFuncName>cnn_core</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/work1/Works/CNN-Core-Generator/hls_streaming</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/cnn_core.cpp</first>
                        <second>cnn_core</second>
                      </first>
                      <second>45</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>806648288</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>5</count>
            <item_version>0</item_version>
            <item>57</item>
            <item>58</item>
            <item>59</item>
            <item>245</item>
            <item>246</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>5</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>44</id>
              <name>_ln47</name>
              <fileName>firmware/cnn_core.cpp</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>47</lineNumber>
              <contextFuncName>cnn_core</contextFuncName>
              <contextNormFuncName>cnn_core</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/work1/Works/CNN-Core-Generator/hls_streaming</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/cnn_core.cpp</first>
                        <second>cnn_core</second>
                      </first>
                      <second>47</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_U0</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>806710528</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>29</count>
            <item_version>0</item_version>
            <item>61</item>
            <item>62</item>
            <item>63</item>
            <item>68</item>
            <item>69</item>
            <item>70</item>
            <item>71</item>
            <item>72</item>
            <item>73</item>
            <item>74</item>
            <item>75</item>
            <item>76</item>
            <item>77</item>
            <item>78</item>
            <item>79</item>
            <item>80</item>
            <item>81</item>
            <item>82</item>
            <item>83</item>
            <item>84</item>
            <item>85</item>
            <item>86</item>
            <item>87</item>
            <item>88</item>
            <item>89</item>
            <item>90</item>
            <item>91</item>
            <item>244</item>
            <item>247</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>6</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>45</id>
              <name>_ln49</name>
              <fileName>firmware/cnn_core.cpp</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>49</lineNumber>
              <contextFuncName>cnn_core</contextFuncName>
              <contextNormFuncName>cnn_core</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/work1/Works/CNN-Core-Generator/hls_streaming</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/cnn_core.cpp</first>
                        <second>cnn_core</second>
                      </first>
                      <second>49</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0</rtlName>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>806683160</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>5</count>
            <item_version>0</item_version>
            <item>65</item>
            <item>66</item>
            <item>67</item>
            <item>243</item>
            <item>248</item>
          </oprand_edges>
          <opcode>call</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>7</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>46</id>
              <name>_ln51</name>
              <fileName>firmware/cnn_core.cpp</fileName>
              <fileDirectory>../.</fileDirectory>
              <lineNumber>51</lineNumber>
              <contextFuncName>cnn_core</contextFuncName>
              <contextNormFuncName>cnn_core</contextNormFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/home/work1/Works/CNN-Core-Generator/hls_streaming</first>
                  <second>
                    <count>1</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>firmware/cnn_core.cpp</first>
                        <second>cnn_core</second>
                      </first>
                      <second>51</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>2935358896</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
          <m_Display>0</m_Display>
          <m_isOnCriticalPath>0</m_isOnCriticalPath>
          <m_isLCDNode>0</m_isLCDNode>
          <m_isStartOfPath>0</m_isStartOfPath>
          <m_delay>0.00</m_delay>
          <m_topoIndex>8</m_topoIndex>
          <m_clusterGroupNumber>-1</m_clusterGroupNumber>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>5</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_11">
          <Value>
            <Obj>
              <type>2</type>
              <id>48</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>806906568</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>64</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_12">
          <Value>
            <Obj>
              <type>2</type>
              <id>52</id>
              <name>first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_s</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>2935712630</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:first_conv_4lane_temporal_cl&lt;array,array&lt;ap_fixed&lt;9,5,5,3,0&gt;,7u&gt;,config3&gt;&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_13">
          <Value>
            <Obj>
              <type>2</type>
              <id>56</id>
              <name>relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_s</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>806791552</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:relu&lt;array&lt;ap_fixed,7u&gt;,array&lt;ap_fixed&lt;16,6,5,3,0&gt;,7u&gt;,relu_config4&gt;&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_14">
          <Value>
            <Obj>
              <type>2</type>
              <id>60</id>
              <name>pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_s</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>0</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:pooling2d_cl&lt;array&lt;ap_fixed,7u&gt;,array&lt;ap_fixed&lt;16,6,5,3,0&gt;,7u&gt;,config5&gt;&gt;</content>
        </item>
        <item class_id_reference="16" object_id="_15">
          <Value>
            <Obj>
              <type>2</type>
              <id>64</id>
              <name>dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_s</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <contextNormFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <control/>
              <opType/>
              <implIndex/>
              <coreName/>
              <isStorage>0</isStorage>
              <storageDepth>0</storageDepth>
              <coreId>0</coreId>
              <rtlModuleName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <const_type>6</const_type>
          <content>&lt;constant:dense&lt;array&lt;ap_fixed,7u&gt;,array&lt;ap_fixed&lt;9,5,5,3,0&gt;,1u&gt;,config7&gt;&gt;</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_16">
          <Obj>
            <type>3</type>
            <id>47</id>
            <name>cnn_core</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <contextNormFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <control/>
            <opType/>
            <implIndex/>
            <coreName/>
            <isStorage>0</isStorage>
            <storageDepth>0</storageDepth>
            <coreId>1043341356</coreId>
            <rtlModuleName/>
          </Obj>
          <node_objs>
            <count>8</count>
            <item_version>0</item_version>
            <item>33</item>
            <item>36</item>
            <item>39</item>
            <item>42</item>
            <item>43</item>
            <item>44</item>
            <item>45</item>
            <item>46</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>45</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_17">
          <id>49</id>
          <edge_type>1</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>33</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_18">
          <id>50</id>
          <edge_type>1</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>36</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_19">
          <id>51</id>
          <edge_type>1</edge_type>
          <source_obj>48</source_obj>
          <sink_obj>39</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_20">
          <id>53</id>
          <edge_type>1</edge_type>
          <source_obj>52</source_obj>
          <sink_obj>42</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_21">
          <id>54</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>42</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_22">
          <id>55</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>42</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_23">
          <id>57</id>
          <edge_type>1</edge_type>
          <source_obj>56</source_obj>
          <sink_obj>43</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_24">
          <id>58</id>
          <edge_type>1</edge_type>
          <source_obj>33</source_obj>
          <sink_obj>43</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_25">
          <id>59</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>43</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_26">
          <id>61</id>
          <edge_type>1</edge_type>
          <source_obj>60</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_27">
          <id>62</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_28">
          <id>63</id>
          <edge_type>1</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_29">
          <id>65</id>
          <edge_type>1</edge_type>
          <source_obj>64</source_obj>
          <sink_obj>45</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_30">
          <id>66</id>
          <edge_type>1</edge_type>
          <source_obj>39</source_obj>
          <sink_obj>45</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_31">
          <id>67</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>45</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_32">
          <id>68</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_33">
          <id>69</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_34">
          <id>70</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>71</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>72</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>73</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>74</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>75</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>76</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>77</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>78</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>79</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>80</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>81</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>82</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>83</id>
          <edge_type>1</edge_type>
          <source_obj>18</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>84</id>
          <edge_type>1</edge_type>
          <source_obj>19</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>85</id>
          <edge_type>1</edge_type>
          <source_obj>20</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>86</id>
          <edge_type>1</edge_type>
          <source_obj>21</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>87</id>
          <edge_type>1</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>88</id>
          <edge_type>1</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>89</id>
          <edge_type>1</edge_type>
          <source_obj>24</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>90</id>
          <edge_type>1</edge_type>
          <source_obj>25</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>91</id>
          <edge_type>1</edge_type>
          <source_obj>26</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>243</id>
          <edge_type>4</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>45</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>244</id>
          <edge_type>4</edge_type>
          <source_obj>43</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>245</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>43</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>246</id>
          <edge_type>4</edge_type>
          <source_obj>42</source_obj>
          <sink_obj>43</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>247</id>
          <edge_type>4</edge_type>
          <source_obj>43</source_obj>
          <sink_obj>44</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>248</id>
          <edge_type>4</edge_type>
          <source_obj>44</source_obj>
          <sink_obj>45</sink_obj>
          <is_back_edge>0</is_back_edge>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_62">
        <mId>1</mId>
        <mTag>cnn_core</mTag>
        <mNormTag>cnn_core</mNormTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>47</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>1041</mMinLatency>
        <mMaxLatency>1041</mMaxLatency>
        <mIsDfPipe>1</mIsDfPipe>
        <mDfPipe class_id="23" tracking_level="1" version="0" object_id="_63">
          <port_list class_id="24" tracking_level="0" version="0">
            <count>2</count>
            <item_version>0</item_version>
            <item class_id="25" tracking_level="1" version="0" object_id="_64">
              <name>input_layer</name>
              <dir>0</dir>
              <type>3</type>
              <need_hs>0</need_hs>
              <top_port class_id="-1"/>
              <chan class_id="-1"/>
            </item>
            <item class_id_reference="25" object_id="_65">
              <name>layer7_out</name>
              <dir>1</dir>
              <type>3</type>
              <need_hs>0</need_hs>
              <top_port class_id="-1"/>
              <chan class_id="-1"/>
            </item>
          </port_list>
          <process_list class_id="27" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_66">
              <type>0</type>
              <name>first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_U0</name>
              <ssdmobj_id>42</ssdmobj_id>
              <pins class_id="29" tracking_level="0" version="0">
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="30" tracking_level="1" version="0" object_id="_67">
                  <port class_id_reference="25" object_id="_68">
                    <name>input_layer</name>
                    <dir>0</dir>
                    <type>3</type>
                    <need_hs>0</need_hs>
                    <top_port class_id_reference="25" object_id_reference="_64"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id="31" tracking_level="1" version="0" object_id="_69">
                    <type>0</type>
                    <name>first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_U0</name>
                    <ssdmobj_id>42</ssdmobj_id>
                  </inst>
                </item>
              </pins>
              <in_source_fork>1</in_source_fork>
              <in_sink_join>0</in_sink_join>
              <flag_in_gui>0</flag_in_gui>
            </item>
            <item class_id_reference="28" object_id="_70">
              <type>0</type>
              <name>relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0</name>
              <ssdmobj_id>43</ssdmobj_id>
              <pins>
                <count>0</count>
                <item_version>0</item_version>
              </pins>
              <in_source_fork>0</in_source_fork>
              <in_sink_join>0</in_sink_join>
              <flag_in_gui>0</flag_in_gui>
            </item>
            <item class_id_reference="28" object_id="_71">
              <type>0</type>
              <name>pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_U0</name>
              <ssdmobj_id>44</ssdmobj_id>
              <pins>
                <count>0</count>
                <item_version>0</item_version>
              </pins>
              <in_source_fork>0</in_source_fork>
              <in_sink_join>0</in_sink_join>
              <flag_in_gui>0</flag_in_gui>
            </item>
            <item class_id_reference="28" object_id="_72">
              <type>0</type>
              <name>dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0</name>
              <ssdmobj_id>45</ssdmobj_id>
              <pins>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id_reference="30" object_id="_73">
                  <port class_id_reference="25" object_id="_74">
                    <name>layer7_out</name>
                    <dir>1</dir>
                    <type>3</type>
                    <need_hs>0</need_hs>
                    <top_port class_id_reference="25" object_id_reference="_65"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id="_75">
                    <type>0</type>
                    <name>dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0</name>
                    <ssdmobj_id>45</ssdmobj_id>
                  </inst>
                </item>
              </pins>
              <in_source_fork>0</in_source_fork>
              <in_sink_join>1</in_sink_join>
              <flag_in_gui>0</flag_in_gui>
            </item>
          </process_list>
          <channel_list class_id="32" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="26" tracking_level="1" version="0" object_id="_76">
              <type>1</type>
              <name>layer3_out</name>
              <ssdmobj_id>33</ssdmobj_id>
              <ctype>0</ctype>
              <depth>336</depth>
              <bitwidth>63</bitwidth>
              <suggested_type>0</suggested_type>
              <suggested_depth>336</suggested_depth>
              <source_list>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id_reference="30" object_id="_77">
                  <port class_id_reference="25" object_id="_78">
                    <name>in</name>
                    <dir>0</dir>
                    <type>3</type>
                    <need_hs>0</need_hs>
                    <top_port class_id="-1"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id_reference="_69"/>
                </item>
              </source_list>
              <sink_list>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id_reference="30" object_id="_79">
                  <port class_id_reference="25" object_id="_80">
                    <name>out</name>
                    <dir>1</dir>
                    <type>3</type>
                    <need_hs>0</need_hs>
                    <top_port class_id="-1"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id="_81">
                    <type>0</type>
                    <name>relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0</name>
                    <ssdmobj_id>43</ssdmobj_id>
                  </inst>
                </item>
              </sink_list>
              <bram_cost>4</bram_cost>
              <uram_cost>0</uram_cost>
              <storage_size>63 336 1</storage_size>
            </item>
            <item class_id_reference="26" object_id="_82">
              <type>1</type>
              <name>layer4_out</name>
              <ssdmobj_id>36</ssdmobj_id>
              <ctype>0</ctype>
              <depth>336</depth>
              <bitwidth>112</bitwidth>
              <suggested_type>0</suggested_type>
              <suggested_depth>336</suggested_depth>
              <source_list>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id_reference="30" object_id="_83">
                  <port class_id_reference="25" object_id="_84">
                    <name>in</name>
                    <dir>0</dir>
                    <type>3</type>
                    <need_hs>0</need_hs>
                    <top_port class_id="-1"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id_reference="_81"/>
                </item>
              </source_list>
              <sink_list>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id_reference="30" object_id="_85">
                  <port class_id_reference="25" object_id="_86">
                    <name>out</name>
                    <dir>1</dir>
                    <type>3</type>
                    <need_hs>0</need_hs>
                    <top_port class_id="-1"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id="_87">
                    <type>0</type>
                    <name>pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_U0</name>
                    <ssdmobj_id>44</ssdmobj_id>
                  </inst>
                </item>
              </sink_list>
              <bram_cost>7</bram_cost>
              <uram_cost>0</uram_cost>
              <storage_size>112 336 1</storage_size>
            </item>
            <item class_id_reference="26" object_id="_88">
              <type>1</type>
              <name>layer5_out</name>
              <ssdmobj_id>39</ssdmobj_id>
              <ctype>0</ctype>
              <depth>168</depth>
              <bitwidth>112</bitwidth>
              <suggested_type>0</suggested_type>
              <suggested_depth>168</suggested_depth>
              <source_list>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id_reference="30" object_id="_89">
                  <port class_id_reference="25" object_id="_90">
                    <name>in</name>
                    <dir>0</dir>
                    <type>3</type>
                    <need_hs>0</need_hs>
                    <top_port class_id="-1"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id_reference="_87"/>
                </item>
              </source_list>
              <sink_list>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id_reference="30" object_id="_91">
                  <port class_id_reference="25" object_id="_92">
                    <name>out</name>
                    <dir>1</dir>
                    <type>3</type>
                    <need_hs>0</need_hs>
                    <top_port class_id="-1"/>
                    <chan class_id="-1"/>
                  </port>
                  <inst class_id_reference="31" object_id_reference="_75"/>
                </item>
              </sink_list>
              <bram_cost>7</bram_cost>
              <uram_cost>0</uram_cost>
              <storage_size>112 168 1</storage_size>
            </item>
          </channel_list>
          <net_list class_id="33" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </net_list>
        </mDfPipe>
      </item>
    </cdfg_regions>
    <fsm class_id="34" tracking_level="1" version="0" object_id="_93">
      <states class_id="35" tracking_level="0" version="0">
        <count>10</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="1" version="0" object_id="_94">
          <id>1</id>
          <operations class_id="37" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="38" tracking_level="1" version="0" object_id="_95">
              <id>33</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_96">
              <id>36</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_97">
              <id>39</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_98">
          <id>2</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_99">
              <id>42</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_100">
          <id>3</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_101">
              <id>42</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_102">
          <id>4</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_103">
              <id>43</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_104">
          <id>5</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_105">
              <id>43</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_106">
          <id>6</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_107">
              <id>44</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_108">
          <id>7</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_109">
              <id>44</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_110">
          <id>8</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_111">
              <id>45</id>
              <stage>2</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_112">
          <id>9</id>
          <operations>
            <count>1</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_113">
              <id>45</id>
              <stage>1</stage>
              <latency>2</latency>
            </item>
          </operations>
        </item>
        <item class_id_reference="36" object_id="_114">
          <id>10</id>
          <operations>
            <count>13</count>
            <item_version>0</item_version>
            <item class_id_reference="38" object_id="_115">
              <id>27</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_116">
              <id>28</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_117">
              <id>29</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_118">
              <id>30</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_119">
              <id>31</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_120">
              <id>32</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_121">
              <id>34</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_122">
              <id>35</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_123">
              <id>37</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_124">
              <id>38</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_125">
              <id>40</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_126">
              <id>41</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="38" object_id="_127">
              <id>46</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="39" tracking_level="0" version="0">
        <count>9</count>
        <item_version>0</item_version>
        <item class_id="40" tracking_level="1" version="0" object_id="_128">
          <inState>1</inState>
          <outState>2</outState>
          <condition class_id="41" tracking_level="0" version="0">
            <id>-1</id>
            <sop class_id="42" tracking_level="0" version="0">
              <count>1</count>
              <item_version>0</item_version>
              <item class_id="43" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_129">
          <inState>2</inState>
          <outState>3</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_130">
          <inState>3</inState>
          <outState>4</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_131">
          <inState>4</inState>
          <outState>5</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_132">
          <inState>5</inState>
          <outState>6</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_133">
          <inState>6</inState>
          <outState>7</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_134">
          <inState>7</inState>
          <outState>8</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_135">
          <inState>8</inState>
          <outState>9</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
        <item class_id_reference="40" object_id="_136">
          <inState>9</inState>
          <outState>10</outState>
          <condition>
            <id>-1</id>
            <sop>
              <count>1</count>
              <item_version>0</item_version>
              <item>
                <count>0</count>
                <item_version>0</item_version>
              </item>
            </sop>
          </condition>
        </item>
      </transitions>
    </fsm>
    <res class_id="44" tracking_level="1" version="0" object_id="_137">
      <dp_component_resource class_id="45" tracking_level="0" version="0">
        <count>7</count>
        <item_version>0</item_version>
        <item class_id="46" tracking_level="0" version="0">
          <first>dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0 (dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_s)</first>
          <second class_id="47" tracking_level="0" version="0">
            <count>3</count>
            <item_version>0</item_version>
            <item class_id="48" tracking_level="0" version="0">
              <first>DSP</first>
              <second>13</second>
            </item>
            <item>
              <first>FF</first>
              <second>27888</second>
            </item>
            <item>
              <first>LUT</first>
              <second>31767</second>
            </item>
          </second>
        </item>
        <item>
          <first>first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_U0 (first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_s)</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>DSP</first>
              <second>4</second>
            </item>
            <item>
              <first>FF</first>
              <second>1198</second>
            </item>
            <item>
              <first>LUT</first>
              <second>3700</second>
            </item>
          </second>
        </item>
        <item>
          <first>pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_U0 (pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_s)</first>
          <second>
            <count>2</count>
            <item_version>0</item_version>
            <item>
              <first>FF</first>
              <second>820</second>
            </item>
            <item>
              <first>LUT</first>
              <second>964</second>
            </item>
          </second>
        </item>
        <item>
          <first>relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0 (relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_s)</first>
          <second>
            <count>2</count>
            <item_version>0</item_version>
            <item>
              <first>FF</first>
              <second>78</second>
            </item>
            <item>
              <first>LUT</first>
              <second>311</second>
            </item>
          </second>
        </item>
        <item>
          <first>start_for_dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0_U (start_for_dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5ibs_U (start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5ibs)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0_U (start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0)</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_component_resource>
      <dp_expression_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>ap_idle ( and ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>2</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>layer3_out_U</first>
          <second>
            <count>6</count>
            <item_version>0</item_version>
            <item>
              <first>(0Depth)</first>
              <second>336</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>63</second>
            </item>
            <item>
              <first>(2Size:D*B)</first>
              <second>21168</second>
            </item>
            <item>
              <first>BRAM</first>
              <second>4</second>
            </item>
            <item>
              <first>FF</first>
              <second>165</second>
            </item>
            <item>
              <first>LUT</first>
              <second>66</second>
            </item>
          </second>
        </item>
        <item>
          <first>layer4_out_U</first>
          <second>
            <count>6</count>
            <item_version>0</item_version>
            <item>
              <first>(0Depth)</first>
              <second>336</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>112</second>
            </item>
            <item>
              <first>(2Size:D*B)</first>
              <second>37632</second>
            </item>
            <item>
              <first>BRAM</first>
              <second>7</second>
            </item>
            <item>
              <first>FF</first>
              <second>165</second>
            </item>
            <item>
              <first>LUT</first>
              <second>66</second>
            </item>
          </second>
        </item>
        <item>
          <first>layer5_out_U</first>
          <second>
            <count>6</count>
            <item_version>0</item_version>
            <item>
              <first>(0Depth)</first>
              <second>168</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>112</second>
            </item>
            <item>
              <first>(2Size:D*B)</first>
              <second>18816</second>
            </item>
            <item>
              <first>BRAM</first>
              <second>7</second>
            </item>
            <item>
              <first>FF</first>
              <second>163</second>
            </item>
            <item>
              <first>LUT</first>
              <second>60</second>
            </item>
          </second>
        </item>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_register_resource>
      <dp_dsp_resource>
        <count>7</count>
        <item_version>0</item_version>
        <item>
          <first>dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_U0</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_U0</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>start_for_dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>start_for_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5ibs_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
        <item>
          <first>start_for_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0_U</first>
          <second>
            <count>0</count>
            <item_version>0</item_version>
          </second>
        </item>
      </dp_dsp_resource>
      <dp_component_map class_id="49" tracking_level="0" version="0">
        <count>4</count>
        <item_version>0</item_version>
        <item class_id="50" tracking_level="0" version="0">
          <first>dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_U0 (dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>45</item>
          </second>
        </item>
        <item>
          <first>first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_U0 (first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>42</item>
          </second>
        </item>
        <item>
          <first>pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_U0 (pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>44</item>
          </second>
        </item>
        <item>
          <first>relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_U0 (relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_s)</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>43</item>
          </second>
        </item>
      </dp_component_map>
      <dp_expression_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_expression_map>
      <dp_fifo_map>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>layer3_out_U</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>89</item>
          </second>
        </item>
        <item>
          <first>layer4_out_U</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>106</item>
          </second>
        </item>
        <item>
          <first>layer5_out_U</first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>123</item>
          </second>
        </item>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="51" tracking_level="0" version="0">
      <count>8</count>
      <item_version>0</item_version>
      <item class_id="52" tracking_level="0" version="0">
        <first>33</first>
        <second class_id="53" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>39</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>42</first>
        <second>
          <first>1</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>43</first>
        <second>
          <first>3</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>44</first>
        <second>
          <first>5</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>45</first>
        <second>
          <first>7</first>
          <second>1</second>
        </second>
      </item>
      <item>
        <first>46</first>
        <second>
          <first>9</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="54" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="55" tracking_level="0" version="0">
        <first>47</first>
        <second class_id="56" tracking_level="0" version="0">
          <first>0</first>
          <second>9</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="57" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="58" tracking_level="1" version="0" object_id="_138">
        <region_name>cnn_core</region_name>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>47</item>
        </basic_blocks>
        <nodes>
          <count>20</count>
          <item_version>0</item_version>
          <item>27</item>
          <item>28</item>
          <item>29</item>
          <item>30</item>
          <item>31</item>
          <item>32</item>
          <item>33</item>
          <item>34</item>
          <item>35</item>
          <item>36</item>
          <item>37</item>
          <item>38</item>
          <item>39</item>
          <item>40</item>
          <item>41</item>
          <item>42</item>
          <item>43</item>
          <item>44</item>
          <item>45</item>
          <item>46</item>
        </nodes>
        <anchor_node>-1</anchor_node>
        <region_type>16</region_type>
        <interval>0</interval>
        <pipe_depth>0</pipe_depth>
        <mDBIIViolationVec class_id="59" tracking_level="0" version="0">
          <count>0</count>
          <item_version>0</item_version>
        </mDBIIViolationVec>
      </item>
    </regions>
    <dp_fu_nodes class_id="60" tracking_level="0" version="0">
      <count>7</count>
      <item_version>0</item_version>
      <item class_id="61" tracking_level="0" version="0">
        <first>100</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>104</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>108</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
      <item>
        <first>112</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>42</item>
          <item>42</item>
        </second>
      </item>
      <item>
        <first>119</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>43</item>
          <item>43</item>
        </second>
      </item>
      <item>
        <first>125</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>44</item>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>179</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>45</item>
          <item>45</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="63" tracking_level="0" version="0">
      <count>3</count>
      <item_version>0</item_version>
      <item class_id="64" tracking_level="0" version="0">
        <first>layer3_out_fu_100</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>layer4_out_fu_104</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>layer5_out_fu_108</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>4</count>
      <item_version>0</item_version>
      <item>
        <first>grp_dense_array_ap_fixed_7u_array_ap_fixed_9_5_5_3_0_1u_config7_s_fu_179</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>45</item>
          <item>45</item>
        </second>
      </item>
      <item>
        <first>grp_first_conv_4lane_temporal_cl_array_array_ap_fixed_9_5_5_3_0_7u_config3_s_fu_112</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>42</item>
          <item>42</item>
        </second>
      </item>
      <item>
        <first>grp_pooling2d_cl_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_config5_s_fu_125</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>44</item>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>grp_relu_array_ap_fixed_7u_array_ap_fixed_16_6_5_3_0_7u_relu_config4_s_fu_119</first>
        <second>
          <count>2</count>
          <item_version>0</item_version>
          <item>43</item>
          <item>43</item>
        </second>
      </item>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="65" tracking_level="0" version="0">
      <count>7</count>
      <item_version>0</item_version>
      <item class_id="66" tracking_level="0" version="0">
        <first class_id="67" tracking_level="0" version="0">
          <first>void_pooling2d_cl_stream_stream_array_ap_fixed_7u_0_line_buffer</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>
          <first>void_pooling2d_cl_stream_stream_array_ap_fixed_7u_0_line_buffer_1</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>
          <first>void_pooling2d_cl_stream_stream_array_ap_fixed_7u_0_line_buffer_2</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>
          <first>void_pooling2d_cl_stream_stream_array_ap_fixed_7u_0_line_buffer_3</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>
          <first>void_pooling2d_cl_stream_stream_array_ap_fixed_7u_0_line_buffer_4</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>
          <first>void_pooling2d_cl_stream_stream_array_ap_fixed_7u_0_line_buffer_5</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
      <item>
        <first>
          <first>void_pooling2d_cl_stream_stream_array_ap_fixed_7u_0_line_buffer_6</first>
          <second>100</second>
        </first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>44</item>
        </second>
      </item>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>186</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>192</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>198</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>3</count>
      <item_version>0</item_version>
      <item>
        <first>layer3_out_reg_186</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>33</item>
        </second>
      </item>
      <item>
        <first>layer4_out_reg_192</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>36</item>
        </second>
      </item>
      <item>
        <first>layer5_out_reg_198</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>39</item>
        </second>
      </item>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="68" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="69" tracking_level="0" version="0">
        <first>input_layer</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>42</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>layer7_out</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>call</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>45</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core>
      <count>0</count>
      <item_version>0</item_version>
    </port2core>
    <node2core>
      <count>7</count>
      <item_version>0</item_version>
      <item>
        <first>33</first>
        <second>
          <first>666</first>
          <second>7</second>
        </second>
      </item>
      <item>
        <first>36</first>
        <second>
          <first>666</first>
          <second>7</second>
        </second>
      </item>
      <item>
        <first>39</first>
        <second>
          <first>666</first>
          <second>7</second>
        </second>
      </item>
      <item>
        <first>42</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
      <item>
        <first>43</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
      <item>
        <first>44</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
      <item>
        <first>45</first>
        <second>
          <first>-1</first>
          <second>-1</second>
        </second>
      </item>
    </node2core>
  </syndb>
</boost_serialization>
