-- ==============================================================
-- Generated by Vitis HLS v2023.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity cnn_core_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_28u_config5_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    layer4x4_out_dout : IN STD_LOGIC_VECTOR (447 downto 0);
    layer4x4_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    layer4x4_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    layer4x4_out_empty_n : IN STD_LOGIC;
    layer4x4_out_read : OUT STD_LOGIC;
    layer5x4_out_din : OUT STD_LOGIC_VECTOR (447 downto 0);
    layer5x4_out_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    layer5x4_out_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    layer5x4_out_full_n : IN STD_LOGIC;
    layer5x4_out_write : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC );
end;


architecture behav of cnn_core_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_28u_config5_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv7_54 : STD_LOGIC_VECTOR (6 downto 0) := "1010100";
    constant ap_const_lv7_1 : STD_LOGIC_VECTOR (6 downto 0) := "0000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_20 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100000";
    constant ap_const_lv32_2F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101111";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_4F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001001111";
    constant ap_const_lv32_50 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001010000";
    constant ap_const_lv32_5F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001011111";
    constant ap_const_lv32_60 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001100000";
    constant ap_const_lv32_6F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001101111";
    constant ap_const_lv32_70 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001110000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_8F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010001111";
    constant ap_const_lv32_90 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010010000";
    constant ap_const_lv32_9F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010011111";
    constant ap_const_lv32_A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010100000";
    constant ap_const_lv32_AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010101111";
    constant ap_const_lv32_B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010110000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_CF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011001111";
    constant ap_const_lv32_D0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011010000";
    constant ap_const_lv32_DF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011011111";
    constant ap_const_lv32_E0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011100000";
    constant ap_const_lv32_EF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011101111";
    constant ap_const_lv32_F0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011110000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_10F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100001111";
    constant ap_const_lv32_110 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100010000";
    constant ap_const_lv32_11F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100011111";
    constant ap_const_lv32_120 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100100000";
    constant ap_const_lv32_12F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100101111";
    constant ap_const_lv32_130 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100110000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_14F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101001111";
    constant ap_const_lv32_150 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101010000";
    constant ap_const_lv32_15F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101011111";
    constant ap_const_lv32_160 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101100000";
    constant ap_const_lv32_16F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101101111";
    constant ap_const_lv32_170 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101110000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_18F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110001111";
    constant ap_const_lv32_190 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110010000";
    constant ap_const_lv32_19F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110011111";
    constant ap_const_lv32_1A0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110100000";
    constant ap_const_lv32_1AF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110101111";
    constant ap_const_lv32_1B0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110110000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal internal_ap_ready : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal on_second_row_reg_289 : STD_LOGIC_VECTOR (0 downto 0);
    signal on_second_row_reg_289_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln430_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal layer4x4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal layer5x4_out_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln430_reg_1401 : STD_LOGIC_VECTOR (0 downto 0);
    signal on_second_row_1_fu_320_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal on_second_row_1_reg_1405 : STD_LOGIC_VECTOR (0 downto 0);
    signal cur_fu_331_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal cur_reg_1410 : STD_LOGIC_VECTOR (15 downto 0);
    signal cur_1_reg_1416 : STD_LOGIC_VECTOR (15 downto 0);
    signal cur_2_reg_1422 : STD_LOGIC_VECTOR (15 downto 0);
    signal cur_3_reg_1428 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_4_reg_1434 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_5_reg_1440 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_6_reg_1446 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_7_reg_1452 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_8_reg_1458 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_9_reg_1464 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_s_reg_1470 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_1_reg_1476 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_2_reg_1482 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_3_reg_1488 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_10_reg_1494 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_11_reg_1500 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_12_reg_1506 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_13_reg_1512 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_14_reg_1518 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_15_reg_1524 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_16_reg_1530 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_17_reg_1536 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_18_reg_1542 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_19_reg_1548 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_20_reg_1554 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_21_reg_1560 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_22_reg_1566 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln433_23_reg_1572 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_phi_mux_on_second_row_phi_fu_292_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_ih_fu_160 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    signal i_ih_2_fu_314_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal ap_sig_allocacmp_i_ih_1 : STD_LOGIC_VECTOR (6 downto 0);
    signal empty_fu_164 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_1_0_0_02_fu_168 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_2_0_0_04_fu_172 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_3_0_0_06_fu_176 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_4_0_0_08_fu_180 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_5_0_0_010_fu_184 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_6_0_0_012_fu_188 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_7_0_0_014_fu_192 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_8_0_0_016_fu_196 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_9_0_0_018_fu_200 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_10_0_0_020_fu_204 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_11_0_0_022_fu_208 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_12_0_0_024_fu_212 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_13_0_0_026_fu_216 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_14_0_0_028_fu_220 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_15_0_0_030_fu_224 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_16_0_0_032_fu_228 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_17_0_0_034_fu_232 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_18_0_0_036_fu_236 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_19_0_0_038_fu_240 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_20_0_0_040_fu_244 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_21_0_0_042_fu_248 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_22_0_0_044_fu_252 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_23_0_0_046_fu_256 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_24_0_0_048_fu_260 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_25_0_0_050_fu_264 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_26_0_0_052_fu_268 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal p_0_27_0_0_054_fu_272 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal icmp_ln448_fu_829_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_1_fu_841_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_2_fu_853_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_3_fu_865_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_4_fu_877_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_5_fu_889_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_6_fu_901_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_7_fu_913_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_8_fu_925_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_9_fu_937_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_10_fu_949_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_11_fu_961_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_12_fu_973_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_13_fu_985_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_14_fu_997_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_15_fu_1009_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_16_fu_1021_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_17_fu_1033_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_18_fu_1045_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_19_fu_1057_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_20_fu_1069_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_21_fu_1081_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_22_fu_1093_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_23_fu_1105_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_24_fu_1117_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_25_fu_1129_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_26_fu_1141_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln448_27_fu_1153_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln448_27_fu_1158_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_26_fu_1146_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_25_fu_1134_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_24_fu_1122_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_23_fu_1110_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_22_fu_1098_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_21_fu_1086_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_20_fu_1074_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_19_fu_1062_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_18_fu_1050_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_17_fu_1038_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_16_fu_1026_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_15_fu_1014_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_14_fu_1002_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_13_fu_990_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_12_fu_978_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_11_fu_966_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_10_fu_954_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_9_fu_942_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_8_fu_930_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_7_fu_918_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_6_fu_906_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_5_fu_894_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_4_fu_882_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_3_fu_870_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_2_fu_858_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_1_fu_846_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal select_ln448_fu_834_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_918 : BOOLEAN;
    signal ap_condition_202 : BOOLEAN;
    signal ap_condition_925 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component cnn_core_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component cnn_core_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => real_start,
        ap_ready => internal_ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((real_start = ap_const_logic_1) and (internal_ap_ready = ap_const_logic_0))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_ih_fu_160_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_202)) then
                if ((icmp_ln430_fu_308_p2 = ap_const_lv1_0)) then 
                    i_ih_fu_160 <= i_ih_2_fu_314_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_ih_fu_160 <= ap_const_lv7_0;
                end if;
            end if; 
        end if;
    end process;

    on_second_row_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_925)) then 
                    on_second_row_reg_289 <= on_second_row_1_reg_1405;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_init = ap_const_logic_1))) then 
                    on_second_row_reg_289 <= ap_const_lv1_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                cur_1_reg_1416 <= layer4x4_out_dout(31 downto 16);
                cur_2_reg_1422 <= layer4x4_out_dout(47 downto 32);
                cur_3_reg_1428 <= layer4x4_out_dout(63 downto 48);
                cur_reg_1410 <= cur_fu_331_p1;
                icmp_ln430_reg_1401 <= icmp_ln430_fu_308_p2;
                on_second_row_reg_289_pp0_iter1_reg <= on_second_row_reg_289;
                trunc_ln433_10_reg_1494 <= layer4x4_out_dout(239 downto 224);
                trunc_ln433_11_reg_1500 <= layer4x4_out_dout(255 downto 240);
                trunc_ln433_12_reg_1506 <= layer4x4_out_dout(271 downto 256);
                trunc_ln433_13_reg_1512 <= layer4x4_out_dout(287 downto 272);
                trunc_ln433_14_reg_1518 <= layer4x4_out_dout(303 downto 288);
                trunc_ln433_15_reg_1524 <= layer4x4_out_dout(319 downto 304);
                trunc_ln433_16_reg_1530 <= layer4x4_out_dout(335 downto 320);
                trunc_ln433_17_reg_1536 <= layer4x4_out_dout(351 downto 336);
                trunc_ln433_18_reg_1542 <= layer4x4_out_dout(367 downto 352);
                trunc_ln433_19_reg_1548 <= layer4x4_out_dout(383 downto 368);
                trunc_ln433_1_reg_1476 <= layer4x4_out_dout(191 downto 176);
                trunc_ln433_20_reg_1554 <= layer4x4_out_dout(399 downto 384);
                trunc_ln433_21_reg_1560 <= layer4x4_out_dout(415 downto 400);
                trunc_ln433_22_reg_1566 <= layer4x4_out_dout(431 downto 416);
                trunc_ln433_23_reg_1572 <= layer4x4_out_dout(447 downto 432);
                trunc_ln433_2_reg_1482 <= layer4x4_out_dout(207 downto 192);
                trunc_ln433_3_reg_1488 <= layer4x4_out_dout(223 downto 208);
                trunc_ln433_4_reg_1434 <= layer4x4_out_dout(79 downto 64);
                trunc_ln433_5_reg_1440 <= layer4x4_out_dout(95 downto 80);
                trunc_ln433_6_reg_1446 <= layer4x4_out_dout(111 downto 96);
                trunc_ln433_7_reg_1452 <= layer4x4_out_dout(127 downto 112);
                trunc_ln433_8_reg_1458 <= layer4x4_out_dout(143 downto 128);
                trunc_ln433_9_reg_1464 <= layer4x4_out_dout(159 downto 144);
                trunc_ln433_s_reg_1470 <= layer4x4_out_dout(175 downto 160);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (on_second_row_reg_289 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                empty_fu_164 <= cur_fu_331_p1;
                p_0_10_0_0_020_fu_204 <= layer4x4_out_dout(175 downto 160);
                p_0_11_0_0_022_fu_208 <= layer4x4_out_dout(191 downto 176);
                p_0_12_0_0_024_fu_212 <= layer4x4_out_dout(207 downto 192);
                p_0_13_0_0_026_fu_216 <= layer4x4_out_dout(223 downto 208);
                p_0_14_0_0_028_fu_220 <= layer4x4_out_dout(239 downto 224);
                p_0_15_0_0_030_fu_224 <= layer4x4_out_dout(255 downto 240);
                p_0_16_0_0_032_fu_228 <= layer4x4_out_dout(271 downto 256);
                p_0_17_0_0_034_fu_232 <= layer4x4_out_dout(287 downto 272);
                p_0_18_0_0_036_fu_236 <= layer4x4_out_dout(303 downto 288);
                p_0_19_0_0_038_fu_240 <= layer4x4_out_dout(319 downto 304);
                p_0_1_0_0_02_fu_168 <= layer4x4_out_dout(31 downto 16);
                p_0_20_0_0_040_fu_244 <= layer4x4_out_dout(335 downto 320);
                p_0_21_0_0_042_fu_248 <= layer4x4_out_dout(351 downto 336);
                p_0_22_0_0_044_fu_252 <= layer4x4_out_dout(367 downto 352);
                p_0_23_0_0_046_fu_256 <= layer4x4_out_dout(383 downto 368);
                p_0_24_0_0_048_fu_260 <= layer4x4_out_dout(399 downto 384);
                p_0_25_0_0_050_fu_264 <= layer4x4_out_dout(415 downto 400);
                p_0_26_0_0_052_fu_268 <= layer4x4_out_dout(431 downto 416);
                p_0_27_0_0_054_fu_272 <= layer4x4_out_dout(447 downto 432);
                p_0_2_0_0_04_fu_172 <= layer4x4_out_dout(47 downto 32);
                p_0_3_0_0_06_fu_176 <= layer4x4_out_dout(63 downto 48);
                p_0_4_0_0_08_fu_180 <= layer4x4_out_dout(79 downto 64);
                p_0_5_0_0_010_fu_184 <= layer4x4_out_dout(95 downto 80);
                p_0_6_0_0_012_fu_188 <= layer4x4_out_dout(111 downto 96);
                p_0_7_0_0_014_fu_192 <= layer4x4_out_dout(127 downto 112);
                p_0_8_0_0_016_fu_196 <= layer4x4_out_dout(143 downto 128);
                p_0_9_0_0_018_fu_200 <= layer4x4_out_dout(159 downto 144);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                on_second_row_1_reg_1405 <= on_second_row_1_fu_320_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1, ap_block_state3_pp0_stage0_iter2, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_pp0_stage0_iter2)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(layer4x4_out_empty_n)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (layer4x4_out_empty_n = ap_const_logic_0);
    end process;


    ap_block_state3_pp0_stage0_iter2_assign_proc : process(layer5x4_out_full_n, on_second_row_reg_289_pp0_iter1_reg)
    begin
                ap_block_state3_pp0_stage0_iter2 <= ((on_second_row_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (layer5x4_out_full_n = ap_const_logic_0));
    end process;


    ap_condition_202_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_202 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0));
    end process;


    ap_condition_918_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln430_reg_1401)
    begin
                ap_condition_918 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln430_reg_1401 = ap_const_lv1_0));
    end process;


    ap_condition_925_assign_proc : process(ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, icmp_ln430_reg_1401)
    begin
                ap_condition_925 <= ((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (icmp_ln430_reg_1401 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln430_fu_308_p2, ap_start_int)
    begin
        if (((icmp_ln430_fu_308_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter1_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter1_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_phi_mux_on_second_row_phi_fu_292_p4_assign_proc : process(ap_CS_fsm_pp0_stage0, on_second_row_1_reg_1405, ap_loop_init, ap_condition_918)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
            if ((ap_const_boolean_1 = ap_condition_918)) then 
                ap_phi_mux_on_second_row_phi_fu_292_p4 <= on_second_row_1_reg_1405;
            elsif ((ap_loop_init = ap_const_logic_1)) then 
                ap_phi_mux_on_second_row_phi_fu_292_p4 <= ap_const_lv1_0;
            else 
                ap_phi_mux_on_second_row_phi_fu_292_p4 <= on_second_row_1_reg_1405;
            end if;
        else 
            ap_phi_mux_on_second_row_phi_fu_292_p4 <= on_second_row_1_reg_1405;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_ih_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_ih_fu_160, ap_start_int)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_start_int = ap_const_logic_1) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_ih_1 <= ap_const_lv7_0;
        else 
            ap_sig_allocacmp_i_ih_1 <= i_ih_fu_160;
        end if; 
    end process;

    cur_fu_331_p1 <= layer4x4_out_dout(16 - 1 downto 0);
    i_ih_2_fu_314_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_ih_1) + unsigned(ap_const_lv7_1));
    icmp_ln430_fu_308_p2 <= "1" when (ap_sig_allocacmp_i_ih_1 = ap_const_lv7_54) else "0";
    icmp_ln448_10_fu_949_p2 <= "1" when (signed(p_0_10_0_0_020_fu_204) > signed(trunc_ln433_s_reg_1470)) else "0";
    icmp_ln448_11_fu_961_p2 <= "1" when (signed(p_0_11_0_0_022_fu_208) > signed(trunc_ln433_1_reg_1476)) else "0";
    icmp_ln448_12_fu_973_p2 <= "1" when (signed(p_0_12_0_0_024_fu_212) > signed(trunc_ln433_2_reg_1482)) else "0";
    icmp_ln448_13_fu_985_p2 <= "1" when (signed(p_0_13_0_0_026_fu_216) > signed(trunc_ln433_3_reg_1488)) else "0";
    icmp_ln448_14_fu_997_p2 <= "1" when (signed(p_0_14_0_0_028_fu_220) > signed(trunc_ln433_10_reg_1494)) else "0";
    icmp_ln448_15_fu_1009_p2 <= "1" when (signed(p_0_15_0_0_030_fu_224) > signed(trunc_ln433_11_reg_1500)) else "0";
    icmp_ln448_16_fu_1021_p2 <= "1" when (signed(p_0_16_0_0_032_fu_228) > signed(trunc_ln433_12_reg_1506)) else "0";
    icmp_ln448_17_fu_1033_p2 <= "1" when (signed(p_0_17_0_0_034_fu_232) > signed(trunc_ln433_13_reg_1512)) else "0";
    icmp_ln448_18_fu_1045_p2 <= "1" when (signed(p_0_18_0_0_036_fu_236) > signed(trunc_ln433_14_reg_1518)) else "0";
    icmp_ln448_19_fu_1057_p2 <= "1" when (signed(p_0_19_0_0_038_fu_240) > signed(trunc_ln433_15_reg_1524)) else "0";
    icmp_ln448_1_fu_841_p2 <= "1" when (signed(p_0_1_0_0_02_fu_168) > signed(cur_1_reg_1416)) else "0";
    icmp_ln448_20_fu_1069_p2 <= "1" when (signed(p_0_20_0_0_040_fu_244) > signed(trunc_ln433_16_reg_1530)) else "0";
    icmp_ln448_21_fu_1081_p2 <= "1" when (signed(p_0_21_0_0_042_fu_248) > signed(trunc_ln433_17_reg_1536)) else "0";
    icmp_ln448_22_fu_1093_p2 <= "1" when (signed(p_0_22_0_0_044_fu_252) > signed(trunc_ln433_18_reg_1542)) else "0";
    icmp_ln448_23_fu_1105_p2 <= "1" when (signed(p_0_23_0_0_046_fu_256) > signed(trunc_ln433_19_reg_1548)) else "0";
    icmp_ln448_24_fu_1117_p2 <= "1" when (signed(p_0_24_0_0_048_fu_260) > signed(trunc_ln433_20_reg_1554)) else "0";
    icmp_ln448_25_fu_1129_p2 <= "1" when (signed(p_0_25_0_0_050_fu_264) > signed(trunc_ln433_21_reg_1560)) else "0";
    icmp_ln448_26_fu_1141_p2 <= "1" when (signed(p_0_26_0_0_052_fu_268) > signed(trunc_ln433_22_reg_1566)) else "0";
    icmp_ln448_27_fu_1153_p2 <= "1" when (signed(p_0_27_0_0_054_fu_272) > signed(trunc_ln433_23_reg_1572)) else "0";
    icmp_ln448_2_fu_853_p2 <= "1" when (signed(p_0_2_0_0_04_fu_172) > signed(cur_2_reg_1422)) else "0";
    icmp_ln448_3_fu_865_p2 <= "1" when (signed(p_0_3_0_0_06_fu_176) > signed(cur_3_reg_1428)) else "0";
    icmp_ln448_4_fu_877_p2 <= "1" when (signed(p_0_4_0_0_08_fu_180) > signed(trunc_ln433_4_reg_1434)) else "0";
    icmp_ln448_5_fu_889_p2 <= "1" when (signed(p_0_5_0_0_010_fu_184) > signed(trunc_ln433_5_reg_1440)) else "0";
    icmp_ln448_6_fu_901_p2 <= "1" when (signed(p_0_6_0_0_012_fu_188) > signed(trunc_ln433_6_reg_1446)) else "0";
    icmp_ln448_7_fu_913_p2 <= "1" when (signed(p_0_7_0_0_014_fu_192) > signed(trunc_ln433_7_reg_1452)) else "0";
    icmp_ln448_8_fu_925_p2 <= "1" when (signed(p_0_8_0_0_016_fu_196) > signed(trunc_ln433_8_reg_1458)) else "0";
    icmp_ln448_9_fu_937_p2 <= "1" when (signed(p_0_9_0_0_018_fu_200) > signed(trunc_ln433_9_reg_1464)) else "0";
    icmp_ln448_fu_829_p2 <= "1" when (signed(empty_fu_164) > signed(cur_reg_1410)) else "0";

    layer4x4_out_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, layer4x4_out_empty_n, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer4x4_out_blk_n <= layer4x4_out_empty_n;
        else 
            layer4x4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    layer4x4_out_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            layer4x4_out_read <= ap_const_logic_1;
        else 
            layer4x4_out_read <= ap_const_logic_0;
        end if; 
    end process;


    layer5x4_out_blk_n_assign_proc : process(ap_enable_reg_pp0_iter2, layer5x4_out_full_n, on_second_row_reg_289_pp0_iter1_reg, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (on_second_row_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            layer5x4_out_blk_n <= layer5x4_out_full_n;
        else 
            layer5x4_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    layer5x4_out_din <= (((((((((((((((((((((((((((select_ln448_27_fu_1158_p3 & select_ln448_26_fu_1146_p3) & select_ln448_25_fu_1134_p3) & select_ln448_24_fu_1122_p3) & select_ln448_23_fu_1110_p3) & select_ln448_22_fu_1098_p3) & select_ln448_21_fu_1086_p3) & select_ln448_20_fu_1074_p3) & select_ln448_19_fu_1062_p3) & select_ln448_18_fu_1050_p3) & select_ln448_17_fu_1038_p3) & select_ln448_16_fu_1026_p3) & select_ln448_15_fu_1014_p3) & select_ln448_14_fu_1002_p3) & select_ln448_13_fu_990_p3) & select_ln448_12_fu_978_p3) & select_ln448_11_fu_966_p3) & select_ln448_10_fu_954_p3) & select_ln448_9_fu_942_p3) & select_ln448_8_fu_930_p3) & select_ln448_7_fu_918_p3) & select_ln448_6_fu_906_p3) & select_ln448_5_fu_894_p3) & select_ln448_4_fu_882_p3) & select_ln448_3_fu_870_p3) & select_ln448_2_fu_858_p3) & select_ln448_1_fu_846_p3) & select_ln448_fu_834_p3);

    layer5x4_out_write_assign_proc : process(ap_enable_reg_pp0_iter2, on_second_row_reg_289_pp0_iter1_reg, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (on_second_row_reg_289_pp0_iter1_reg = ap_const_lv1_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_1))) then 
            layer5x4_out_write <= ap_const_logic_1;
        else 
            layer5x4_out_write <= ap_const_logic_0;
        end if; 
    end process;

    on_second_row_1_fu_320_p2 <= (ap_phi_mux_on_second_row_phi_fu_292_p4 xor ap_const_lv1_1);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_full_n = ap_const_logic_0) and (start_once_reg = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    select_ln448_10_fu_954_p3 <= 
        p_0_10_0_0_020_fu_204 when (icmp_ln448_10_fu_949_p2(0) = '1') else 
        trunc_ln433_s_reg_1470;
    select_ln448_11_fu_966_p3 <= 
        p_0_11_0_0_022_fu_208 when (icmp_ln448_11_fu_961_p2(0) = '1') else 
        trunc_ln433_1_reg_1476;
    select_ln448_12_fu_978_p3 <= 
        p_0_12_0_0_024_fu_212 when (icmp_ln448_12_fu_973_p2(0) = '1') else 
        trunc_ln433_2_reg_1482;
    select_ln448_13_fu_990_p3 <= 
        p_0_13_0_0_026_fu_216 when (icmp_ln448_13_fu_985_p2(0) = '1') else 
        trunc_ln433_3_reg_1488;
    select_ln448_14_fu_1002_p3 <= 
        p_0_14_0_0_028_fu_220 when (icmp_ln448_14_fu_997_p2(0) = '1') else 
        trunc_ln433_10_reg_1494;
    select_ln448_15_fu_1014_p3 <= 
        p_0_15_0_0_030_fu_224 when (icmp_ln448_15_fu_1009_p2(0) = '1') else 
        trunc_ln433_11_reg_1500;
    select_ln448_16_fu_1026_p3 <= 
        p_0_16_0_0_032_fu_228 when (icmp_ln448_16_fu_1021_p2(0) = '1') else 
        trunc_ln433_12_reg_1506;
    select_ln448_17_fu_1038_p3 <= 
        p_0_17_0_0_034_fu_232 when (icmp_ln448_17_fu_1033_p2(0) = '1') else 
        trunc_ln433_13_reg_1512;
    select_ln448_18_fu_1050_p3 <= 
        p_0_18_0_0_036_fu_236 when (icmp_ln448_18_fu_1045_p2(0) = '1') else 
        trunc_ln433_14_reg_1518;
    select_ln448_19_fu_1062_p3 <= 
        p_0_19_0_0_038_fu_240 when (icmp_ln448_19_fu_1057_p2(0) = '1') else 
        trunc_ln433_15_reg_1524;
    select_ln448_1_fu_846_p3 <= 
        p_0_1_0_0_02_fu_168 when (icmp_ln448_1_fu_841_p2(0) = '1') else 
        cur_1_reg_1416;
    select_ln448_20_fu_1074_p3 <= 
        p_0_20_0_0_040_fu_244 when (icmp_ln448_20_fu_1069_p2(0) = '1') else 
        trunc_ln433_16_reg_1530;
    select_ln448_21_fu_1086_p3 <= 
        p_0_21_0_0_042_fu_248 when (icmp_ln448_21_fu_1081_p2(0) = '1') else 
        trunc_ln433_17_reg_1536;
    select_ln448_22_fu_1098_p3 <= 
        p_0_22_0_0_044_fu_252 when (icmp_ln448_22_fu_1093_p2(0) = '1') else 
        trunc_ln433_18_reg_1542;
    select_ln448_23_fu_1110_p3 <= 
        p_0_23_0_0_046_fu_256 when (icmp_ln448_23_fu_1105_p2(0) = '1') else 
        trunc_ln433_19_reg_1548;
    select_ln448_24_fu_1122_p3 <= 
        p_0_24_0_0_048_fu_260 when (icmp_ln448_24_fu_1117_p2(0) = '1') else 
        trunc_ln433_20_reg_1554;
    select_ln448_25_fu_1134_p3 <= 
        p_0_25_0_0_050_fu_264 when (icmp_ln448_25_fu_1129_p2(0) = '1') else 
        trunc_ln433_21_reg_1560;
    select_ln448_26_fu_1146_p3 <= 
        p_0_26_0_0_052_fu_268 when (icmp_ln448_26_fu_1141_p2(0) = '1') else 
        trunc_ln433_22_reg_1566;
    select_ln448_27_fu_1158_p3 <= 
        p_0_27_0_0_054_fu_272 when (icmp_ln448_27_fu_1153_p2(0) = '1') else 
        trunc_ln433_23_reg_1572;
    select_ln448_2_fu_858_p3 <= 
        p_0_2_0_0_04_fu_172 when (icmp_ln448_2_fu_853_p2(0) = '1') else 
        cur_2_reg_1422;
    select_ln448_3_fu_870_p3 <= 
        p_0_3_0_0_06_fu_176 when (icmp_ln448_3_fu_865_p2(0) = '1') else 
        cur_3_reg_1428;
    select_ln448_4_fu_882_p3 <= 
        p_0_4_0_0_08_fu_180 when (icmp_ln448_4_fu_877_p2(0) = '1') else 
        trunc_ln433_4_reg_1434;
    select_ln448_5_fu_894_p3 <= 
        p_0_5_0_0_010_fu_184 when (icmp_ln448_5_fu_889_p2(0) = '1') else 
        trunc_ln433_5_reg_1440;
    select_ln448_6_fu_906_p3 <= 
        p_0_6_0_0_012_fu_188 when (icmp_ln448_6_fu_901_p2(0) = '1') else 
        trunc_ln433_6_reg_1446;
    select_ln448_7_fu_918_p3 <= 
        p_0_7_0_0_014_fu_192 when (icmp_ln448_7_fu_913_p2(0) = '1') else 
        trunc_ln433_7_reg_1452;
    select_ln448_8_fu_930_p3 <= 
        p_0_8_0_0_016_fu_196 when (icmp_ln448_8_fu_925_p2(0) = '1') else 
        trunc_ln433_8_reg_1458;
    select_ln448_9_fu_942_p3 <= 
        p_0_9_0_0_018_fu_200 when (icmp_ln448_9_fu_937_p2(0) = '1') else 
        trunc_ln433_9_reg_1464;
    select_ln448_fu_834_p3 <= 
        empty_fu_164 when (icmp_ln448_fu_829_p2(0) = '1') else 
        cur_reg_1410;
    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((real_start = ap_const_logic_1) and (start_once_reg = ap_const_logic_0))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

end behav;
