// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module cnn_core_dense_wide_stream_array_array_ap_fixed_1u_config9_Pipeline_DenseValues (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        layer6_out_x4_dout,
        layer6_out_x4_num_data_valid,
        layer6_out_x4_fifo_cap,
        layer6_out_x4_empty_n,
        layer6_out_x4_read,
        accumulator_out,
        accumulator_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [799:0] layer6_out_x4_dout;
input  [2:0] layer6_out_x4_num_data_valid;
input  [2:0] layer6_out_x4_fifo_cap;
input   layer6_out_x4_empty_n;
output   layer6_out_x4_read;
output  [23:0] accumulator_out;
output   accumulator_out_ap_vld;

reg ap_idle;
reg layer6_out_x4_read;
reg accumulator_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_idle_pp0;
reg   [0:0] icmp_ln301_reg_4377;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln299_fu_881_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [6:0] w9_ravel_packed_address0;
reg    w9_ravel_packed_ce0;
wire   [237:0] w9_ravel_packed_q0;
reg    layer6_out_x4_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
reg   [6:0] step_1_reg_4368;
reg   [0:0] icmp_ln299_reg_4373;
reg   [0:0] icmp_ln299_reg_4373_pp0_iter2_reg;
reg   [0:0] icmp_ln299_reg_4373_pp0_iter3_reg;
reg   [0:0] icmp_ln299_reg_4373_pp0_iter4_reg;
reg   [0:0] icmp_ln299_reg_4373_pp0_iter5_reg;
wire   [0:0] icmp_ln301_fu_897_p2;
wire   [0:0] empty_fu_903_p2;
reg   [0:0] empty_reg_4381;
reg   [0:0] empty_reg_4381_pp0_iter2_reg;
wire   [15:0] mul_ln73_fu_2396_p2;
reg  signed [15:0] mul_ln73_reg_4430;
reg  signed [5:0] lane_weight_1_reg_4435;
wire   [9:0] a_28_fu_2412_p3;
reg  signed [9:0] a_28_reg_4440;
reg   [5:0] lane_weight_2_reg_4445;
reg  signed [5:0] lane_weight_2_reg_4445_pp0_iter4_reg;
wire   [9:0] a_29_fu_2429_p3;
reg   [9:0] a_29_reg_4450;
reg  signed [9:0] a_29_reg_4450_pp0_iter4_reg;
wire   [15:0] mul_ln73_3_fu_2461_p2;
reg  signed [15:0] mul_ln73_3_reg_4455;
reg  signed [5:0] lane_weight_4_reg_4460;
wire   [9:0] a_31_fu_2477_p3;
reg  signed [9:0] a_31_reg_4465;
wire   [15:0] mul_ln73_5_fu_2509_p2;
reg  signed [15:0] mul_ln73_5_reg_4470;
reg  signed [5:0] lane_weight_6_reg_4475;
wire   [9:0] a_33_fu_2525_p3;
reg  signed [9:0] a_33_reg_4480;
reg   [5:0] lane_weight_7_reg_4485;
reg  signed [5:0] lane_weight_7_reg_4485_pp0_iter4_reg;
wire   [9:0] a_34_fu_2542_p3;
reg   [9:0] a_34_reg_4490;
reg  signed [9:0] a_34_reg_4490_pp0_iter4_reg;
wire   [15:0] mul_ln73_8_fu_2574_p2;
reg  signed [15:0] mul_ln73_8_reg_4495;
reg  signed [5:0] lane_weight_9_reg_4500;
wire   [9:0] a_36_fu_2590_p3;
reg  signed [9:0] a_36_reg_4505;
wire   [15:0] mul_ln73_10_fu_2622_p2;
reg  signed [15:0] mul_ln73_10_reg_4510;
reg  signed [5:0] lane_weight_11_reg_4515;
wire   [9:0] a_38_fu_2638_p3;
reg  signed [9:0] a_38_reg_4520;
reg   [5:0] lane_weight_12_reg_4525;
reg  signed [5:0] lane_weight_12_reg_4525_pp0_iter4_reg;
wire   [9:0] a_39_fu_2655_p3;
reg   [9:0] a_39_reg_4530;
reg  signed [9:0] a_39_reg_4530_pp0_iter4_reg;
wire   [15:0] mul_ln73_13_fu_2687_p2;
reg  signed [15:0] mul_ln73_13_reg_4535;
reg  signed [5:0] lane_weight_14_reg_4540;
wire   [9:0] a_41_fu_2703_p3;
reg  signed [9:0] a_41_reg_4545;
wire   [15:0] mul_ln73_15_fu_2735_p2;
reg  signed [15:0] mul_ln73_15_reg_4550;
reg  signed [5:0] lane_weight_16_reg_4555;
wire   [9:0] a_43_fu_2751_p3;
reg  signed [9:0] a_43_reg_4560;
reg   [5:0] lane_weight_17_reg_4565;
reg  signed [5:0] lane_weight_17_reg_4565_pp0_iter4_reg;
wire   [9:0] a_44_fu_2768_p3;
reg   [9:0] a_44_reg_4570;
reg  signed [9:0] a_44_reg_4570_pp0_iter4_reg;
wire   [15:0] mul_ln73_18_fu_2800_p2;
reg  signed [15:0] mul_ln73_18_reg_4575;
reg  signed [5:0] lane_weight_19_reg_4580;
wire   [9:0] a_46_fu_2816_p3;
reg  signed [9:0] a_46_reg_4585;
wire   [15:0] mul_ln73_20_fu_2848_p2;
reg  signed [15:0] mul_ln73_20_reg_4590;
reg  signed [5:0] lane_weight_21_reg_4595;
wire   [9:0] a_48_fu_2864_p3;
reg  signed [9:0] a_48_reg_4600;
reg   [5:0] lane_weight_22_reg_4605;
reg  signed [5:0] lane_weight_22_reg_4605_pp0_iter4_reg;
wire   [9:0] a_49_fu_2881_p3;
reg   [9:0] a_49_reg_4610;
reg  signed [9:0] a_49_reg_4610_pp0_iter4_reg;
wire   [15:0] mul_ln73_23_fu_2913_p2;
reg  signed [15:0] mul_ln73_23_reg_4615;
reg  signed [5:0] lane_weight_24_reg_4620;
wire   [9:0] a_51_fu_2929_p3;
reg  signed [9:0] a_51_reg_4625;
wire   [15:0] mul_ln73_25_fu_2961_p2;
reg  signed [15:0] mul_ln73_25_reg_4630;
reg  signed [5:0] lane_weight_26_reg_4635;
wire   [9:0] a_53_fu_2977_p3;
reg  signed [9:0] a_53_reg_4640;
reg   [5:0] lane_weight_27_reg_4645;
reg  signed [5:0] lane_weight_27_reg_4645_pp0_iter4_reg;
wire   [9:0] a_54_fu_2994_p3;
reg   [9:0] a_54_reg_4650;
reg  signed [9:0] a_54_reg_4650_pp0_iter4_reg;
wire   [15:0] mul_ln73_28_fu_3026_p2;
reg  signed [15:0] mul_ln73_28_reg_4655;
reg  signed [5:0] lane_weight_29_reg_4660;
wire   [9:0] a_56_fu_3042_p3;
reg  signed [9:0] a_56_reg_4665;
wire   [15:0] mul_ln73_30_fu_3074_p2;
reg  signed [15:0] mul_ln73_30_reg_4670;
reg  signed [5:0] lane_weight_31_reg_4675;
wire   [9:0] a_58_fu_3090_p3;
reg  signed [9:0] a_58_reg_4680;
reg   [5:0] lane_weight_32_reg_4685;
reg  signed [5:0] lane_weight_32_reg_4685_pp0_iter4_reg;
wire   [9:0] a_59_fu_3107_p3;
reg   [9:0] a_59_reg_4690;
reg  signed [9:0] a_59_reg_4690_pp0_iter4_reg;
wire   [15:0] mul_ln73_33_fu_3139_p2;
reg  signed [15:0] mul_ln73_33_reg_4695;
reg  signed [5:0] lane_weight_34_reg_4700;
wire   [9:0] a_61_fu_3155_p3;
reg  signed [9:0] a_61_reg_4705;
wire   [15:0] mul_ln73_35_fu_3187_p2;
reg  signed [15:0] mul_ln73_35_reg_4710;
reg  signed [5:0] lane_weight_36_reg_4715;
wire   [9:0] a_63_fu_3203_p3;
reg  signed [9:0] a_63_reg_4720;
reg   [5:0] lane_weight_37_reg_4725;
reg  signed [5:0] lane_weight_37_reg_4725_pp0_iter4_reg;
wire   [9:0] a_64_fu_3220_p3;
reg   [9:0] a_64_reg_4730;
reg  signed [9:0] a_64_reg_4730_pp0_iter4_reg;
wire   [15:0] mul_ln73_38_fu_3252_p2;
reg  signed [15:0] mul_ln73_38_reg_4735;
reg  signed [3:0] tmp_s_reg_4740;
wire   [9:0] a_66_fu_3268_p3;
reg  signed [9:0] a_66_reg_4745;
wire  signed [16:0] grp_fu_3674_p3;
reg  signed [16:0] add_ln326_reg_4750;
wire  signed [16:0] grp_fu_3682_p3;
reg  signed [16:0] add_ln326_1_reg_4755;
wire  signed [16:0] grp_fu_3690_p3;
reg  signed [16:0] add_ln326_4_reg_4760;
wire  signed [16:0] grp_fu_3698_p3;
reg  signed [16:0] add_ln326_5_reg_4765;
wire  signed [16:0] grp_fu_3706_p3;
reg  signed [16:0] add_ln326_9_reg_4770;
wire  signed [16:0] grp_fu_3714_p3;
reg  signed [16:0] add_ln326_10_reg_4775;
wire  signed [16:0] grp_fu_3722_p3;
reg  signed [16:0] add_ln326_13_reg_4780;
wire  signed [16:0] grp_fu_3730_p3;
reg  signed [16:0] add_ln326_14_reg_4785;
wire  signed [16:0] grp_fu_3738_p3;
reg  signed [16:0] add_ln326_19_reg_4790;
wire  signed [16:0] grp_fu_3746_p3;
reg  signed [16:0] add_ln326_20_reg_4795;
wire  signed [16:0] grp_fu_3754_p3;
reg  signed [16:0] add_ln326_23_reg_4800;
wire  signed [16:0] grp_fu_3762_p3;
reg  signed [16:0] add_ln326_24_reg_4805;
wire  signed [16:0] grp_fu_3770_p3;
reg  signed [16:0] add_ln326_28_reg_4810;
wire  signed [16:0] grp_fu_3778_p3;
reg  signed [16:0] add_ln326_29_reg_4815;
wire  signed [16:0] grp_fu_3786_p3;
reg  signed [16:0] add_ln326_32_reg_4820;
wire  signed [15:0] grp_fu_3794_p3;
reg  signed [15:0] add_ln326_33_reg_4825;
wire   [17:0] add_ln326_3_fu_3470_p2;
reg   [17:0] add_ln326_3_reg_4830;
wire   [17:0] add_ln326_7_fu_3482_p2;
reg   [17:0] add_ln326_7_reg_4835;
wire   [17:0] add_ln326_12_fu_3494_p2;
reg   [17:0] add_ln326_12_reg_4840;
wire   [17:0] add_ln326_16_fu_3506_p2;
reg   [17:0] add_ln326_16_reg_4845;
wire   [17:0] add_ln326_22_fu_3518_p2;
reg   [17:0] add_ln326_22_reg_4850;
wire   [17:0] add_ln326_26_fu_3530_p2;
reg   [17:0] add_ln326_26_reg_4855;
wire   [17:0] add_ln326_31_fu_3542_p2;
reg   [17:0] add_ln326_31_reg_4860;
wire   [17:0] add_ln326_35_fu_3557_p2;
reg   [17:0] add_ln326_35_reg_4865;
wire   [20:0] add_ln326_38_fu_3647_p2;
reg   [20:0] add_ln326_38_reg_4870;
wire   [63:0] zext_ln299_fu_939_p1;
reg   [23:0] accumulator_fu_502;
wire   [23:0] accumulator_1_fu_3659_p2;
wire    ap_loop_init;
reg   [31:0] group_fu_506;
wire   [31:0] group_3_fu_921_p3;
reg   [6:0] step_fu_510;
wire   [6:0] add_ln299_fu_887_p2;
reg   [9:0] input_word_fu_514;
wire   [9:0] input_word_158_fu_943_p1;
reg   [9:0] input_word_1_fu_518;
reg   [9:0] input_word_2_fu_522;
reg   [9:0] input_word_3_fu_526;
reg   [9:0] input_word_4_fu_530;
reg   [9:0] input_word_5_fu_534;
reg   [9:0] input_word_6_fu_538;
reg   [9:0] input_word_7_fu_542;
reg   [9:0] input_word_8_fu_546;
reg   [9:0] input_word_9_fu_550;
reg   [9:0] input_word_10_fu_554;
reg   [9:0] input_word_11_fu_558;
reg   [9:0] input_word_12_fu_562;
reg   [9:0] input_word_13_fu_566;
reg   [9:0] input_word_14_fu_570;
reg   [9:0] input_word_15_fu_574;
reg   [9:0] input_word_16_fu_578;
reg   [9:0] input_word_17_fu_582;
reg   [9:0] input_word_18_fu_586;
reg   [9:0] input_word_19_fu_590;
reg   [9:0] input_word_20_fu_594;
reg   [9:0] input_word_21_fu_598;
reg   [9:0] input_word_22_fu_602;
reg   [9:0] input_word_23_fu_606;
reg   [9:0] input_word_24_fu_610;
reg   [9:0] input_word_25_fu_614;
reg   [9:0] input_word_26_fu_618;
reg   [9:0] input_word_27_fu_622;
reg   [9:0] input_word_28_fu_626;
reg   [9:0] input_word_29_fu_630;
reg   [9:0] input_word_30_fu_634;
reg   [9:0] input_word_31_fu_638;
reg   [9:0] input_word_32_fu_642;
reg   [9:0] input_word_33_fu_646;
reg   [9:0] input_word_34_fu_650;
reg   [9:0] input_word_35_fu_654;
reg   [9:0] input_word_36_fu_658;
reg   [9:0] input_word_37_fu_662;
reg   [9:0] input_word_38_fu_666;
reg   [9:0] input_word_39_fu_670;
reg   [9:0] input_word_40_fu_674;
reg   [9:0] input_word_41_fu_678;
reg   [9:0] input_word_42_fu_682;
reg   [9:0] input_word_43_fu_686;
reg   [9:0] input_word_44_fu_690;
reg   [9:0] input_word_45_fu_694;
reg   [9:0] input_word_46_fu_698;
reg   [9:0] input_word_47_fu_702;
reg   [9:0] input_word_48_fu_706;
reg   [9:0] input_word_49_fu_710;
reg   [9:0] input_word_50_fu_714;
reg   [9:0] input_word_51_fu_718;
reg   [9:0] input_word_52_fu_722;
reg   [9:0] input_word_53_fu_726;
reg   [9:0] input_word_54_fu_730;
reg   [9:0] input_word_55_fu_734;
reg   [9:0] input_word_56_fu_738;
reg   [9:0] input_word_57_fu_742;
reg   [9:0] input_word_58_fu_746;
reg   [9:0] input_word_59_fu_750;
reg   [9:0] input_word_60_fu_754;
reg   [9:0] input_word_61_fu_758;
reg   [9:0] input_word_62_fu_762;
reg   [9:0] input_word_63_fu_766;
reg   [9:0] input_word_64_fu_770;
reg   [9:0] input_word_65_fu_774;
reg   [9:0] input_word_66_fu_778;
reg   [9:0] input_word_67_fu_782;
reg   [9:0] input_word_68_fu_786;
reg   [9:0] input_word_69_fu_790;
reg   [9:0] input_word_70_fu_794;
reg   [9:0] input_word_71_fu_798;
reg   [9:0] input_word_72_fu_802;
reg   [9:0] input_word_73_fu_806;
reg   [9:0] input_word_74_fu_810;
reg   [9:0] input_word_75_fu_814;
reg   [9:0] input_word_76_fu_818;
reg   [9:0] input_word_77_fu_822;
reg   [9:0] input_word_78_fu_826;
reg   [9:0] input_word_79_fu_830;
reg    ap_block_pp0_stage0_01001;
wire   [6:0] trunc_ln295_fu_893_p1;
wire   [0:0] icmp_ln329_fu_909_p2;
wire   [31:0] add_ln329_fu_915_p2;
wire  signed [9:0] a_fu_2381_p3;
wire  signed [5:0] lane_weight_fu_2377_p1;
wire  signed [9:0] a_30_fu_2446_p3;
wire  signed [5:0] lane_weight_3_fu_2436_p4;
wire  signed [9:0] a_32_fu_2494_p3;
wire  signed [5:0] lane_weight_5_fu_2484_p4;
wire  signed [9:0] a_35_fu_2559_p3;
wire  signed [5:0] lane_weight_8_fu_2549_p4;
wire  signed [9:0] a_37_fu_2607_p3;
wire  signed [5:0] lane_weight_10_fu_2597_p4;
wire  signed [9:0] a_40_fu_2672_p3;
wire  signed [5:0] lane_weight_13_fu_2662_p4;
wire  signed [9:0] a_42_fu_2720_p3;
wire  signed [5:0] lane_weight_15_fu_2710_p4;
wire  signed [9:0] a_45_fu_2785_p3;
wire  signed [5:0] lane_weight_18_fu_2775_p4;
wire  signed [9:0] a_47_fu_2833_p3;
wire  signed [5:0] lane_weight_20_fu_2823_p4;
wire  signed [9:0] a_50_fu_2898_p3;
wire  signed [5:0] lane_weight_23_fu_2888_p4;
wire  signed [9:0] a_52_fu_2946_p3;
wire  signed [5:0] lane_weight_25_fu_2936_p4;
wire  signed [9:0] a_55_fu_3011_p3;
wire  signed [5:0] lane_weight_28_fu_3001_p4;
wire  signed [9:0] a_57_fu_3059_p3;
wire  signed [5:0] lane_weight_30_fu_3049_p4;
wire  signed [9:0] a_60_fu_3124_p3;
wire  signed [5:0] lane_weight_33_fu_3114_p4;
wire  signed [9:0] a_62_fu_3172_p3;
wire  signed [5:0] lane_weight_35_fu_3162_p4;
wire  signed [9:0] a_65_fu_3237_p3;
wire  signed [5:0] lane_weight_38_fu_3227_p4;
wire  signed [16:0] grp_fu_3801_p3;
wire  signed [17:0] sext_ln326_40_fu_3467_p1;
wire  signed [17:0] sext_ln326_39_fu_3464_p1;
wire  signed [16:0] grp_fu_3809_p3;
wire  signed [17:0] sext_ln326_43_fu_3479_p1;
wire  signed [17:0] sext_ln326_42_fu_3476_p1;
wire  signed [16:0] grp_fu_3817_p3;
wire  signed [17:0] sext_ln326_47_fu_3491_p1;
wire  signed [17:0] sext_ln326_46_fu_3488_p1;
wire  signed [16:0] grp_fu_3825_p3;
wire  signed [17:0] sext_ln326_50_fu_3503_p1;
wire  signed [17:0] sext_ln326_49_fu_3500_p1;
wire  signed [16:0] grp_fu_3833_p3;
wire  signed [17:0] sext_ln326_55_fu_3515_p1;
wire  signed [17:0] sext_ln326_54_fu_3512_p1;
wire  signed [16:0] grp_fu_3841_p3;
wire  signed [17:0] sext_ln326_58_fu_3527_p1;
wire  signed [17:0] sext_ln326_57_fu_3524_p1;
wire  signed [16:0] grp_fu_3849_p3;
wire  signed [17:0] sext_ln326_62_fu_3539_p1;
wire  signed [17:0] sext_ln326_61_fu_3536_p1;
wire  signed [16:0] grp_fu_3857_p3;
wire  signed [17:0] sext_ln326_66_fu_3554_p1;
wire  signed [17:0] sext_ln326_64_fu_3548_p1;
wire  signed [18:0] sext_ln326_44_fu_3566_p1;
wire  signed [18:0] sext_ln326_41_fu_3563_p1;
wire   [18:0] add_ln326_8_fu_3569_p2;
wire  signed [18:0] sext_ln326_51_fu_3582_p1;
wire  signed [18:0] sext_ln326_48_fu_3579_p1;
wire   [18:0] add_ln326_17_fu_3585_p2;
wire  signed [19:0] sext_ln326_52_fu_3591_p1;
wire  signed [19:0] sext_ln326_45_fu_3575_p1;
wire   [19:0] add_ln326_18_fu_3595_p2;
wire  signed [18:0] sext_ln326_59_fu_3608_p1;
wire  signed [18:0] sext_ln326_56_fu_3605_p1;
wire   [18:0] add_ln326_27_fu_3611_p2;
wire  signed [18:0] sext_ln326_67_fu_3624_p1;
wire  signed [18:0] sext_ln326_63_fu_3621_p1;
wire   [18:0] add_ln326_36_fu_3627_p2;
wire  signed [19:0] sext_ln326_68_fu_3633_p1;
wire  signed [19:0] sext_ln326_60_fu_3617_p1;
wire   [19:0] add_ln326_37_fu_3637_p2;
wire  signed [20:0] sext_ln326_69_fu_3643_p1;
wire  signed [20:0] sext_ln326_53_fu_3601_p1;
wire  signed [23:0] sext_ln326_70_fu_3656_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 accumulator_fu_502 = 24'd0;
#0 group_fu_506 = 32'd0;
#0 step_fu_510 = 7'd0;
#0 input_word_fu_514 = 10'd0;
#0 input_word_1_fu_518 = 10'd0;
#0 input_word_2_fu_522 = 10'd0;
#0 input_word_3_fu_526 = 10'd0;
#0 input_word_4_fu_530 = 10'd0;
#0 input_word_5_fu_534 = 10'd0;
#0 input_word_6_fu_538 = 10'd0;
#0 input_word_7_fu_542 = 10'd0;
#0 input_word_8_fu_546 = 10'd0;
#0 input_word_9_fu_550 = 10'd0;
#0 input_word_10_fu_554 = 10'd0;
#0 input_word_11_fu_558 = 10'd0;
#0 input_word_12_fu_562 = 10'd0;
#0 input_word_13_fu_566 = 10'd0;
#0 input_word_14_fu_570 = 10'd0;
#0 input_word_15_fu_574 = 10'd0;
#0 input_word_16_fu_578 = 10'd0;
#0 input_word_17_fu_582 = 10'd0;
#0 input_word_18_fu_586 = 10'd0;
#0 input_word_19_fu_590 = 10'd0;
#0 input_word_20_fu_594 = 10'd0;
#0 input_word_21_fu_598 = 10'd0;
#0 input_word_22_fu_602 = 10'd0;
#0 input_word_23_fu_606 = 10'd0;
#0 input_word_24_fu_610 = 10'd0;
#0 input_word_25_fu_614 = 10'd0;
#0 input_word_26_fu_618 = 10'd0;
#0 input_word_27_fu_622 = 10'd0;
#0 input_word_28_fu_626 = 10'd0;
#0 input_word_29_fu_630 = 10'd0;
#0 input_word_30_fu_634 = 10'd0;
#0 input_word_31_fu_638 = 10'd0;
#0 input_word_32_fu_642 = 10'd0;
#0 input_word_33_fu_646 = 10'd0;
#0 input_word_34_fu_650 = 10'd0;
#0 input_word_35_fu_654 = 10'd0;
#0 input_word_36_fu_658 = 10'd0;
#0 input_word_37_fu_662 = 10'd0;
#0 input_word_38_fu_666 = 10'd0;
#0 input_word_39_fu_670 = 10'd0;
#0 input_word_40_fu_674 = 10'd0;
#0 input_word_41_fu_678 = 10'd0;
#0 input_word_42_fu_682 = 10'd0;
#0 input_word_43_fu_686 = 10'd0;
#0 input_word_44_fu_690 = 10'd0;
#0 input_word_45_fu_694 = 10'd0;
#0 input_word_46_fu_698 = 10'd0;
#0 input_word_47_fu_702 = 10'd0;
#0 input_word_48_fu_706 = 10'd0;
#0 input_word_49_fu_710 = 10'd0;
#0 input_word_50_fu_714 = 10'd0;
#0 input_word_51_fu_718 = 10'd0;
#0 input_word_52_fu_722 = 10'd0;
#0 input_word_53_fu_726 = 10'd0;
#0 input_word_54_fu_730 = 10'd0;
#0 input_word_55_fu_734 = 10'd0;
#0 input_word_56_fu_738 = 10'd0;
#0 input_word_57_fu_742 = 10'd0;
#0 input_word_58_fu_746 = 10'd0;
#0 input_word_59_fu_750 = 10'd0;
#0 input_word_60_fu_754 = 10'd0;
#0 input_word_61_fu_758 = 10'd0;
#0 input_word_62_fu_762 = 10'd0;
#0 input_word_63_fu_766 = 10'd0;
#0 input_word_64_fu_770 = 10'd0;
#0 input_word_65_fu_774 = 10'd0;
#0 input_word_66_fu_778 = 10'd0;
#0 input_word_67_fu_782 = 10'd0;
#0 input_word_68_fu_786 = 10'd0;
#0 input_word_69_fu_790 = 10'd0;
#0 input_word_70_fu_794 = 10'd0;
#0 input_word_71_fu_798 = 10'd0;
#0 input_word_72_fu_802 = 10'd0;
#0 input_word_73_fu_806 = 10'd0;
#0 input_word_74_fu_810 = 10'd0;
#0 input_word_75_fu_814 = 10'd0;
#0 input_word_76_fu_818 = 10'd0;
#0 input_word_77_fu_822 = 10'd0;
#0 input_word_78_fu_826 = 10'd0;
#0 input_word_79_fu_830 = 10'd0;
#0 ap_done_reg = 1'b0;
end

cnn_core_dense_wide_stream_array_array_ap_fixed_1u_config9_Pipeline_DenseValues_w9_ravbkb #(
    .DataWidth( 238 ),
    .AddressRange( 124 ),
    .AddressWidth( 7 ))
w9_ravel_packed_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w9_ravel_packed_address0),
    .ce0(w9_ravel_packed_ce0),
    .q0(w9_ravel_packed_q0)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U8(
    .din0(a_fu_2381_p3),
    .din1(lane_weight_fu_2377_p1),
    .dout(mul_ln73_fu_2396_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U9(
    .din0(a_30_fu_2446_p3),
    .din1(lane_weight_3_fu_2436_p4),
    .dout(mul_ln73_3_fu_2461_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U10(
    .din0(a_32_fu_2494_p3),
    .din1(lane_weight_5_fu_2484_p4),
    .dout(mul_ln73_5_fu_2509_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U11(
    .din0(a_35_fu_2559_p3),
    .din1(lane_weight_8_fu_2549_p4),
    .dout(mul_ln73_8_fu_2574_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U12(
    .din0(a_37_fu_2607_p3),
    .din1(lane_weight_10_fu_2597_p4),
    .dout(mul_ln73_10_fu_2622_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U13(
    .din0(a_40_fu_2672_p3),
    .din1(lane_weight_13_fu_2662_p4),
    .dout(mul_ln73_13_fu_2687_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U14(
    .din0(a_42_fu_2720_p3),
    .din1(lane_weight_15_fu_2710_p4),
    .dout(mul_ln73_15_fu_2735_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U15(
    .din0(a_45_fu_2785_p3),
    .din1(lane_weight_18_fu_2775_p4),
    .dout(mul_ln73_18_fu_2800_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U16(
    .din0(a_47_fu_2833_p3),
    .din1(lane_weight_20_fu_2823_p4),
    .dout(mul_ln73_20_fu_2848_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U17(
    .din0(a_50_fu_2898_p3),
    .din1(lane_weight_23_fu_2888_p4),
    .dout(mul_ln73_23_fu_2913_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U18(
    .din0(a_52_fu_2946_p3),
    .din1(lane_weight_25_fu_2936_p4),
    .dout(mul_ln73_25_fu_2961_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U19(
    .din0(a_55_fu_3011_p3),
    .din1(lane_weight_28_fu_3001_p4),
    .dout(mul_ln73_28_fu_3026_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U20(
    .din0(a_57_fu_3059_p3),
    .din1(lane_weight_30_fu_3049_p4),
    .dout(mul_ln73_30_fu_3074_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U21(
    .din0(a_60_fu_3124_p3),
    .din1(lane_weight_33_fu_3114_p4),
    .dout(mul_ln73_33_fu_3139_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U22(
    .din0(a_62_fu_3172_p3),
    .din1(lane_weight_35_fu_3162_p4),
    .dout(mul_ln73_35_fu_3187_p2)
);

cnn_core_mul_10s_6s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 16 ))
mul_10s_6s_16_1_1_U23(
    .din0(a_65_fu_3237_p3),
    .din1(lane_weight_38_fu_3227_p4),
    .dout(mul_ln73_38_fu_3252_p2)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U24(
    .din0(a_28_reg_4440),
    .din1(lane_weight_1_reg_4435),
    .din2(mul_ln73_reg_4430),
    .dout(grp_fu_3674_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U25(
    .din0(a_31_reg_4465),
    .din1(lane_weight_4_reg_4460),
    .din2(mul_ln73_3_reg_4455),
    .dout(grp_fu_3682_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U26(
    .din0(a_33_reg_4480),
    .din1(lane_weight_6_reg_4475),
    .din2(mul_ln73_5_reg_4470),
    .dout(grp_fu_3690_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U27(
    .din0(a_36_reg_4505),
    .din1(lane_weight_9_reg_4500),
    .din2(mul_ln73_8_reg_4495),
    .dout(grp_fu_3698_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U28(
    .din0(a_38_reg_4520),
    .din1(lane_weight_11_reg_4515),
    .din2(mul_ln73_10_reg_4510),
    .dout(grp_fu_3706_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U29(
    .din0(a_41_reg_4545),
    .din1(lane_weight_14_reg_4540),
    .din2(mul_ln73_13_reg_4535),
    .dout(grp_fu_3714_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U30(
    .din0(a_43_reg_4560),
    .din1(lane_weight_16_reg_4555),
    .din2(mul_ln73_15_reg_4550),
    .dout(grp_fu_3722_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U31(
    .din0(a_46_reg_4585),
    .din1(lane_weight_19_reg_4580),
    .din2(mul_ln73_18_reg_4575),
    .dout(grp_fu_3730_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U32(
    .din0(a_48_reg_4600),
    .din1(lane_weight_21_reg_4595),
    .din2(mul_ln73_20_reg_4590),
    .dout(grp_fu_3738_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U33(
    .din0(a_51_reg_4625),
    .din1(lane_weight_24_reg_4620),
    .din2(mul_ln73_23_reg_4615),
    .dout(grp_fu_3746_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U34(
    .din0(a_53_reg_4640),
    .din1(lane_weight_26_reg_4635),
    .din2(mul_ln73_25_reg_4630),
    .dout(grp_fu_3754_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U35(
    .din0(a_56_reg_4665),
    .din1(lane_weight_29_reg_4660),
    .din2(mul_ln73_28_reg_4655),
    .dout(grp_fu_3762_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U36(
    .din0(a_58_reg_4680),
    .din1(lane_weight_31_reg_4675),
    .din2(mul_ln73_30_reg_4670),
    .dout(grp_fu_3770_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U37(
    .din0(a_61_reg_4705),
    .din1(lane_weight_34_reg_4700),
    .din2(mul_ln73_33_reg_4695),
    .dout(grp_fu_3778_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U38(
    .din0(a_63_reg_4720),
    .din1(lane_weight_36_reg_4715),
    .din2(mul_ln73_35_reg_4710),
    .dout(grp_fu_3786_p3)
);

cnn_core_mac_muladd_10s_4s_16s_16_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
mac_muladd_10s_4s_16s_16_1_1_U39(
    .din0(a_66_reg_4745),
    .din1(tmp_s_reg_4740),
    .din2(mul_ln73_38_reg_4735),
    .dout(grp_fu_3794_p3)
);

cnn_core_mac_muladd_10s_6s_17s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_17s_17_1_1_U40(
    .din0(a_29_reg_4450_pp0_iter4_reg),
    .din1(lane_weight_2_reg_4445_pp0_iter4_reg),
    .din2(add_ln326_1_reg_4755),
    .dout(grp_fu_3801_p3)
);

cnn_core_mac_muladd_10s_6s_17s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_17s_17_1_1_U41(
    .din0(a_34_reg_4490_pp0_iter4_reg),
    .din1(lane_weight_7_reg_4485_pp0_iter4_reg),
    .din2(add_ln326_5_reg_4765),
    .dout(grp_fu_3809_p3)
);

cnn_core_mac_muladd_10s_6s_17s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_17s_17_1_1_U42(
    .din0(a_39_reg_4530_pp0_iter4_reg),
    .din1(lane_weight_12_reg_4525_pp0_iter4_reg),
    .din2(add_ln326_10_reg_4775),
    .dout(grp_fu_3817_p3)
);

cnn_core_mac_muladd_10s_6s_17s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_17s_17_1_1_U43(
    .din0(a_44_reg_4570_pp0_iter4_reg),
    .din1(lane_weight_17_reg_4565_pp0_iter4_reg),
    .din2(add_ln326_14_reg_4785),
    .dout(grp_fu_3825_p3)
);

cnn_core_mac_muladd_10s_6s_17s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_17s_17_1_1_U44(
    .din0(a_49_reg_4610_pp0_iter4_reg),
    .din1(lane_weight_22_reg_4605_pp0_iter4_reg),
    .din2(add_ln326_20_reg_4795),
    .dout(grp_fu_3833_p3)
);

cnn_core_mac_muladd_10s_6s_17s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_17s_17_1_1_U45(
    .din0(a_54_reg_4650_pp0_iter4_reg),
    .din1(lane_weight_27_reg_4645_pp0_iter4_reg),
    .din2(add_ln326_24_reg_4805),
    .dout(grp_fu_3841_p3)
);

cnn_core_mac_muladd_10s_6s_17s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 17 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_17s_17_1_1_U46(
    .din0(a_59_reg_4690_pp0_iter4_reg),
    .din1(lane_weight_32_reg_4685_pp0_iter4_reg),
    .din2(add_ln326_29_reg_4815),
    .dout(grp_fu_3849_p3)
);

cnn_core_mac_muladd_10s_6s_16s_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 10 ),
    .din1_WIDTH( 6 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 17 ))
mac_muladd_10s_6s_16s_17_1_1_U47(
    .din0(a_64_reg_4730_pp0_iter4_reg),
    .din1(lane_weight_37_reg_4725_pp0_iter4_reg),
    .din2(add_ln326_33_reg_4825),
    .dout(grp_fu_3857_p3)
);

cnn_core_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            accumulator_fu_502 <= 24'd16777024;
        end else if ((ap_enable_reg_pp0_iter7 == 1'b1)) begin
            accumulator_fu_502 <= accumulator_1_fu_3659_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            group_fu_506 <= 32'd0;
        end else if (((icmp_ln299_fu_881_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            group_fu_506 <= group_3_fu_921_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            step_fu_510 <= 7'd0;
        end else if (((icmp_ln299_fu_881_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            step_fu_510 <= add_ln299_fu_887_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        a_28_reg_4440 <= a_28_fu_2412_p3;
        a_29_reg_4450 <= a_29_fu_2429_p3;
        a_29_reg_4450_pp0_iter4_reg <= a_29_reg_4450;
        a_31_reg_4465 <= a_31_fu_2477_p3;
        a_33_reg_4480 <= a_33_fu_2525_p3;
        a_34_reg_4490 <= a_34_fu_2542_p3;
        a_34_reg_4490_pp0_iter4_reg <= a_34_reg_4490;
        a_36_reg_4505 <= a_36_fu_2590_p3;
        a_38_reg_4520 <= a_38_fu_2638_p3;
        a_39_reg_4530 <= a_39_fu_2655_p3;
        a_39_reg_4530_pp0_iter4_reg <= a_39_reg_4530;
        a_41_reg_4545 <= a_41_fu_2703_p3;
        a_43_reg_4560 <= a_43_fu_2751_p3;
        a_44_reg_4570 <= a_44_fu_2768_p3;
        a_44_reg_4570_pp0_iter4_reg <= a_44_reg_4570;
        a_46_reg_4585 <= a_46_fu_2816_p3;
        a_48_reg_4600 <= a_48_fu_2864_p3;
        a_49_reg_4610 <= a_49_fu_2881_p3;
        a_49_reg_4610_pp0_iter4_reg <= a_49_reg_4610;
        a_51_reg_4625 <= a_51_fu_2929_p3;
        a_53_reg_4640 <= a_53_fu_2977_p3;
        a_54_reg_4650 <= a_54_fu_2994_p3;
        a_54_reg_4650_pp0_iter4_reg <= a_54_reg_4650;
        a_56_reg_4665 <= a_56_fu_3042_p3;
        a_58_reg_4680 <= a_58_fu_3090_p3;
        a_59_reg_4690 <= a_59_fu_3107_p3;
        a_59_reg_4690_pp0_iter4_reg <= a_59_reg_4690;
        a_61_reg_4705 <= a_61_fu_3155_p3;
        a_63_reg_4720 <= a_63_fu_3203_p3;
        a_64_reg_4730 <= a_64_fu_3220_p3;
        a_64_reg_4730_pp0_iter4_reg <= a_64_reg_4730;
        a_66_reg_4745 <= a_66_fu_3268_p3;
        add_ln326_12_reg_4840 <= add_ln326_12_fu_3494_p2;
        add_ln326_16_reg_4845 <= add_ln326_16_fu_3506_p2;
        add_ln326_22_reg_4850 <= add_ln326_22_fu_3518_p2;
        add_ln326_26_reg_4855 <= add_ln326_26_fu_3530_p2;
        add_ln326_31_reg_4860 <= add_ln326_31_fu_3542_p2;
        add_ln326_35_reg_4865 <= add_ln326_35_fu_3557_p2;
        add_ln326_38_reg_4870 <= add_ln326_38_fu_3647_p2;
        add_ln326_3_reg_4830 <= add_ln326_3_fu_3470_p2;
        add_ln326_7_reg_4835 <= add_ln326_7_fu_3482_p2;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        empty_reg_4381_pp0_iter2_reg <= empty_reg_4381;
        icmp_ln299_reg_4373_pp0_iter2_reg <= icmp_ln299_reg_4373;
        icmp_ln299_reg_4373_pp0_iter3_reg <= icmp_ln299_reg_4373_pp0_iter2_reg;
        icmp_ln299_reg_4373_pp0_iter4_reg <= icmp_ln299_reg_4373_pp0_iter3_reg;
        icmp_ln299_reg_4373_pp0_iter5_reg <= icmp_ln299_reg_4373_pp0_iter4_reg;
        lane_weight_11_reg_4515 <= {{w9_ravel_packed_q0[71:66]}};
        lane_weight_12_reg_4525 <= {{w9_ravel_packed_q0[77:72]}};
        lane_weight_12_reg_4525_pp0_iter4_reg <= lane_weight_12_reg_4525;
        lane_weight_14_reg_4540 <= {{w9_ravel_packed_q0[89:84]}};
        lane_weight_16_reg_4555 <= {{w9_ravel_packed_q0[101:96]}};
        lane_weight_17_reg_4565 <= {{w9_ravel_packed_q0[107:102]}};
        lane_weight_17_reg_4565_pp0_iter4_reg <= lane_weight_17_reg_4565;
        lane_weight_19_reg_4580 <= {{w9_ravel_packed_q0[119:114]}};
        lane_weight_1_reg_4435 <= {{w9_ravel_packed_q0[11:6]}};
        lane_weight_21_reg_4595 <= {{w9_ravel_packed_q0[131:126]}};
        lane_weight_22_reg_4605 <= {{w9_ravel_packed_q0[137:132]}};
        lane_weight_22_reg_4605_pp0_iter4_reg <= lane_weight_22_reg_4605;
        lane_weight_24_reg_4620 <= {{w9_ravel_packed_q0[149:144]}};
        lane_weight_26_reg_4635 <= {{w9_ravel_packed_q0[161:156]}};
        lane_weight_27_reg_4645 <= {{w9_ravel_packed_q0[167:162]}};
        lane_weight_27_reg_4645_pp0_iter4_reg <= lane_weight_27_reg_4645;
        lane_weight_29_reg_4660 <= {{w9_ravel_packed_q0[179:174]}};
        lane_weight_2_reg_4445 <= {{w9_ravel_packed_q0[17:12]}};
        lane_weight_2_reg_4445_pp0_iter4_reg <= lane_weight_2_reg_4445;
        lane_weight_31_reg_4675 <= {{w9_ravel_packed_q0[191:186]}};
        lane_weight_32_reg_4685 <= {{w9_ravel_packed_q0[197:192]}};
        lane_weight_32_reg_4685_pp0_iter4_reg <= lane_weight_32_reg_4685;
        lane_weight_34_reg_4700 <= {{w9_ravel_packed_q0[209:204]}};
        lane_weight_36_reg_4715 <= {{w9_ravel_packed_q0[221:216]}};
        lane_weight_37_reg_4725 <= {{w9_ravel_packed_q0[227:222]}};
        lane_weight_37_reg_4725_pp0_iter4_reg <= lane_weight_37_reg_4725;
        lane_weight_4_reg_4460 <= {{w9_ravel_packed_q0[29:24]}};
        lane_weight_6_reg_4475 <= {{w9_ravel_packed_q0[41:36]}};
        lane_weight_7_reg_4485 <= {{w9_ravel_packed_q0[47:42]}};
        lane_weight_7_reg_4485_pp0_iter4_reg <= lane_weight_7_reg_4485;
        lane_weight_9_reg_4500 <= {{w9_ravel_packed_q0[59:54]}};
        mul_ln73_10_reg_4510 <= mul_ln73_10_fu_2622_p2;
        mul_ln73_13_reg_4535 <= mul_ln73_13_fu_2687_p2;
        mul_ln73_15_reg_4550 <= mul_ln73_15_fu_2735_p2;
        mul_ln73_18_reg_4575 <= mul_ln73_18_fu_2800_p2;
        mul_ln73_20_reg_4590 <= mul_ln73_20_fu_2848_p2;
        mul_ln73_23_reg_4615 <= mul_ln73_23_fu_2913_p2;
        mul_ln73_25_reg_4630 <= mul_ln73_25_fu_2961_p2;
        mul_ln73_28_reg_4655 <= mul_ln73_28_fu_3026_p2;
        mul_ln73_30_reg_4670 <= mul_ln73_30_fu_3074_p2;
        mul_ln73_33_reg_4695 <= mul_ln73_33_fu_3139_p2;
        mul_ln73_35_reg_4710 <= mul_ln73_35_fu_3187_p2;
        mul_ln73_38_reg_4735 <= mul_ln73_38_fu_3252_p2;
        mul_ln73_3_reg_4455 <= mul_ln73_3_fu_2461_p2;
        mul_ln73_5_reg_4470 <= mul_ln73_5_fu_2509_p2;
        mul_ln73_8_reg_4495 <= mul_ln73_8_fu_2574_p2;
        mul_ln73_reg_4430 <= mul_ln73_fu_2396_p2;
        tmp_s_reg_4740 <= {{w9_ravel_packed_q0[237:234]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        add_ln326_10_reg_4775 <= grp_fu_3714_p3;
        add_ln326_13_reg_4780 <= grp_fu_3722_p3;
        add_ln326_14_reg_4785 <= grp_fu_3730_p3;
        add_ln326_19_reg_4790 <= grp_fu_3738_p3;
        add_ln326_1_reg_4755 <= grp_fu_3682_p3;
        add_ln326_20_reg_4795 <= grp_fu_3746_p3;
        add_ln326_23_reg_4800 <= grp_fu_3754_p3;
        add_ln326_24_reg_4805 <= grp_fu_3762_p3;
        add_ln326_28_reg_4810 <= grp_fu_3770_p3;
        add_ln326_29_reg_4815 <= grp_fu_3778_p3;
        add_ln326_32_reg_4820 <= grp_fu_3786_p3;
        add_ln326_33_reg_4825 <= grp_fu_3794_p3;
        add_ln326_4_reg_4760 <= grp_fu_3690_p3;
        add_ln326_5_reg_4765 <= grp_fu_3698_p3;
        add_ln326_9_reg_4770 <= grp_fu_3706_p3;
        add_ln326_reg_4750 <= grp_fu_3674_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        empty_reg_4381 <= empty_fu_903_p2;
        icmp_ln299_reg_4373 <= icmp_ln299_fu_881_p2;
        icmp_ln301_reg_4377 <= icmp_ln301_fu_897_p2;
        step_1_reg_4368 <= step_fu_510;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln301_reg_4377 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        input_word_10_fu_554 <= {{layer6_out_x4_dout[109:100]}};
        input_word_11_fu_558 <= {{layer6_out_x4_dout[119:110]}};
        input_word_12_fu_562 <= {{layer6_out_x4_dout[129:120]}};
        input_word_13_fu_566 <= {{layer6_out_x4_dout[139:130]}};
        input_word_14_fu_570 <= {{layer6_out_x4_dout[149:140]}};
        input_word_15_fu_574 <= {{layer6_out_x4_dout[159:150]}};
        input_word_16_fu_578 <= {{layer6_out_x4_dout[169:160]}};
        input_word_17_fu_582 <= {{layer6_out_x4_dout[179:170]}};
        input_word_18_fu_586 <= {{layer6_out_x4_dout[189:180]}};
        input_word_19_fu_590 <= {{layer6_out_x4_dout[199:190]}};
        input_word_1_fu_518 <= {{layer6_out_x4_dout[19:10]}};
        input_word_20_fu_594 <= {{layer6_out_x4_dout[209:200]}};
        input_word_21_fu_598 <= {{layer6_out_x4_dout[219:210]}};
        input_word_22_fu_602 <= {{layer6_out_x4_dout[229:220]}};
        input_word_23_fu_606 <= {{layer6_out_x4_dout[239:230]}};
        input_word_24_fu_610 <= {{layer6_out_x4_dout[249:240]}};
        input_word_25_fu_614 <= {{layer6_out_x4_dout[259:250]}};
        input_word_26_fu_618 <= {{layer6_out_x4_dout[269:260]}};
        input_word_27_fu_622 <= {{layer6_out_x4_dout[279:270]}};
        input_word_28_fu_626 <= {{layer6_out_x4_dout[289:280]}};
        input_word_29_fu_630 <= {{layer6_out_x4_dout[299:290]}};
        input_word_2_fu_522 <= {{layer6_out_x4_dout[29:20]}};
        input_word_30_fu_634 <= {{layer6_out_x4_dout[309:300]}};
        input_word_31_fu_638 <= {{layer6_out_x4_dout[319:310]}};
        input_word_32_fu_642 <= {{layer6_out_x4_dout[329:320]}};
        input_word_33_fu_646 <= {{layer6_out_x4_dout[339:330]}};
        input_word_34_fu_650 <= {{layer6_out_x4_dout[349:340]}};
        input_word_35_fu_654 <= {{layer6_out_x4_dout[359:350]}};
        input_word_36_fu_658 <= {{layer6_out_x4_dout[369:360]}};
        input_word_37_fu_662 <= {{layer6_out_x4_dout[379:370]}};
        input_word_38_fu_666 <= {{layer6_out_x4_dout[389:380]}};
        input_word_39_fu_670 <= {{layer6_out_x4_dout[399:390]}};
        input_word_3_fu_526 <= {{layer6_out_x4_dout[39:30]}};
        input_word_40_fu_674 <= {{layer6_out_x4_dout[409:400]}};
        input_word_41_fu_678 <= {{layer6_out_x4_dout[419:410]}};
        input_word_42_fu_682 <= {{layer6_out_x4_dout[429:420]}};
        input_word_43_fu_686 <= {{layer6_out_x4_dout[439:430]}};
        input_word_44_fu_690 <= {{layer6_out_x4_dout[449:440]}};
        input_word_45_fu_694 <= {{layer6_out_x4_dout[459:450]}};
        input_word_46_fu_698 <= {{layer6_out_x4_dout[469:460]}};
        input_word_47_fu_702 <= {{layer6_out_x4_dout[479:470]}};
        input_word_48_fu_706 <= {{layer6_out_x4_dout[489:480]}};
        input_word_49_fu_710 <= {{layer6_out_x4_dout[499:490]}};
        input_word_4_fu_530 <= {{layer6_out_x4_dout[49:40]}};
        input_word_50_fu_714 <= {{layer6_out_x4_dout[509:500]}};
        input_word_51_fu_718 <= {{layer6_out_x4_dout[519:510]}};
        input_word_52_fu_722 <= {{layer6_out_x4_dout[529:520]}};
        input_word_53_fu_726 <= {{layer6_out_x4_dout[539:530]}};
        input_word_54_fu_730 <= {{layer6_out_x4_dout[549:540]}};
        input_word_55_fu_734 <= {{layer6_out_x4_dout[559:550]}};
        input_word_56_fu_738 <= {{layer6_out_x4_dout[569:560]}};
        input_word_57_fu_742 <= {{layer6_out_x4_dout[579:570]}};
        input_word_58_fu_746 <= {{layer6_out_x4_dout[589:580]}};
        input_word_59_fu_750 <= {{layer6_out_x4_dout[599:590]}};
        input_word_5_fu_534 <= {{layer6_out_x4_dout[59:50]}};
        input_word_60_fu_754 <= {{layer6_out_x4_dout[609:600]}};
        input_word_61_fu_758 <= {{layer6_out_x4_dout[619:610]}};
        input_word_62_fu_762 <= {{layer6_out_x4_dout[629:620]}};
        input_word_63_fu_766 <= {{layer6_out_x4_dout[639:630]}};
        input_word_64_fu_770 <= {{layer6_out_x4_dout[649:640]}};
        input_word_65_fu_774 <= {{layer6_out_x4_dout[659:650]}};
        input_word_66_fu_778 <= {{layer6_out_x4_dout[669:660]}};
        input_word_67_fu_782 <= {{layer6_out_x4_dout[679:670]}};
        input_word_68_fu_786 <= {{layer6_out_x4_dout[689:680]}};
        input_word_69_fu_790 <= {{layer6_out_x4_dout[699:690]}};
        input_word_6_fu_538 <= {{layer6_out_x4_dout[69:60]}};
        input_word_70_fu_794 <= {{layer6_out_x4_dout[709:700]}};
        input_word_71_fu_798 <= {{layer6_out_x4_dout[719:710]}};
        input_word_72_fu_802 <= {{layer6_out_x4_dout[729:720]}};
        input_word_73_fu_806 <= {{layer6_out_x4_dout[739:730]}};
        input_word_74_fu_810 <= {{layer6_out_x4_dout[749:740]}};
        input_word_75_fu_814 <= {{layer6_out_x4_dout[759:750]}};
        input_word_76_fu_818 <= {{layer6_out_x4_dout[769:760]}};
        input_word_77_fu_822 <= {{layer6_out_x4_dout[779:770]}};
        input_word_78_fu_826 <= {{layer6_out_x4_dout[789:780]}};
        input_word_79_fu_830 <= {{layer6_out_x4_dout[799:790]}};
        input_word_7_fu_542 <= {{layer6_out_x4_dout[79:70]}};
        input_word_8_fu_546 <= {{layer6_out_x4_dout[89:80]}};
        input_word_9_fu_550 <= {{layer6_out_x4_dout[99:90]}};
        input_word_fu_514 <= input_word_158_fu_943_p1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln299_reg_4373_pp0_iter5_reg == 1'd1))) begin
        accumulator_out_ap_vld = 1'b1;
    end else begin
        accumulator_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln299_fu_881_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter6_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (icmp_ln301_reg_4377 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer6_out_x4_blk_n = layer6_out_x4_empty_n;
    end else begin
        layer6_out_x4_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln301_reg_4377 == 1'd1) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        layer6_out_x4_read = 1'b1;
    end else begin
        layer6_out_x4_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        w9_ravel_packed_ce0 = 1'b1;
    end else begin
        w9_ravel_packed_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_28_fu_2412_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_41_fu_678 : input_word_1_fu_518);

assign a_29_fu_2429_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_42_fu_682 : input_word_2_fu_522);

assign a_30_fu_2446_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_43_fu_686 : input_word_3_fu_526);

assign a_31_fu_2477_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_44_fu_690 : input_word_4_fu_530);

assign a_32_fu_2494_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_45_fu_694 : input_word_5_fu_534);

assign a_33_fu_2525_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_46_fu_698 : input_word_6_fu_538);

assign a_34_fu_2542_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_47_fu_702 : input_word_7_fu_542);

assign a_35_fu_2559_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_48_fu_706 : input_word_8_fu_546);

assign a_36_fu_2590_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_49_fu_710 : input_word_9_fu_550);

assign a_37_fu_2607_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_50_fu_714 : input_word_10_fu_554);

assign a_38_fu_2638_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_51_fu_718 : input_word_11_fu_558);

assign a_39_fu_2655_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_52_fu_722 : input_word_12_fu_562);

assign a_40_fu_2672_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_53_fu_726 : input_word_13_fu_566);

assign a_41_fu_2703_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_54_fu_730 : input_word_14_fu_570);

assign a_42_fu_2720_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_55_fu_734 : input_word_15_fu_574);

assign a_43_fu_2751_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_56_fu_738 : input_word_16_fu_578);

assign a_44_fu_2768_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_57_fu_742 : input_word_17_fu_582);

assign a_45_fu_2785_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_58_fu_746 : input_word_18_fu_586);

assign a_46_fu_2816_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_59_fu_750 : input_word_19_fu_590);

assign a_47_fu_2833_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_60_fu_754 : input_word_20_fu_594);

assign a_48_fu_2864_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_61_fu_758 : input_word_21_fu_598);

assign a_49_fu_2881_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_62_fu_762 : input_word_22_fu_602);

assign a_50_fu_2898_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_63_fu_766 : input_word_23_fu_606);

assign a_51_fu_2929_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_64_fu_770 : input_word_24_fu_610);

assign a_52_fu_2946_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_65_fu_774 : input_word_25_fu_614);

assign a_53_fu_2977_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_66_fu_778 : input_word_26_fu_618);

assign a_54_fu_2994_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_67_fu_782 : input_word_27_fu_622);

assign a_55_fu_3011_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_68_fu_786 : input_word_28_fu_626);

assign a_56_fu_3042_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_69_fu_790 : input_word_29_fu_630);

assign a_57_fu_3059_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_70_fu_794 : input_word_30_fu_634);

assign a_58_fu_3090_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_71_fu_798 : input_word_31_fu_638);

assign a_59_fu_3107_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_72_fu_802 : input_word_32_fu_642);

assign a_60_fu_3124_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_73_fu_806 : input_word_33_fu_646);

assign a_61_fu_3155_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_74_fu_810 : input_word_34_fu_650);

assign a_62_fu_3172_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_75_fu_814 : input_word_35_fu_654);

assign a_63_fu_3203_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_76_fu_818 : input_word_36_fu_658);

assign a_64_fu_3220_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_77_fu_822 : input_word_37_fu_662);

assign a_65_fu_3237_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_78_fu_826 : input_word_38_fu_666);

assign a_66_fu_3268_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_79_fu_830 : input_word_39_fu_670);

assign a_fu_2381_p3 = ((empty_reg_4381_pp0_iter2_reg[0:0] == 1'b1) ? input_word_40_fu_674 : input_word_fu_514);

assign accumulator_1_fu_3659_p2 = ($signed(accumulator_fu_502) + $signed(sext_ln326_70_fu_3656_p1));

assign accumulator_out = accumulator_fu_502;

assign add_ln299_fu_887_p2 = (step_fu_510 + 7'd1);

assign add_ln326_12_fu_3494_p2 = ($signed(sext_ln326_47_fu_3491_p1) + $signed(sext_ln326_46_fu_3488_p1));

assign add_ln326_16_fu_3506_p2 = ($signed(sext_ln326_50_fu_3503_p1) + $signed(sext_ln326_49_fu_3500_p1));

assign add_ln326_17_fu_3585_p2 = ($signed(sext_ln326_51_fu_3582_p1) + $signed(sext_ln326_48_fu_3579_p1));

assign add_ln326_18_fu_3595_p2 = ($signed(sext_ln326_52_fu_3591_p1) + $signed(sext_ln326_45_fu_3575_p1));

assign add_ln326_22_fu_3518_p2 = ($signed(sext_ln326_55_fu_3515_p1) + $signed(sext_ln326_54_fu_3512_p1));

assign add_ln326_26_fu_3530_p2 = ($signed(sext_ln326_58_fu_3527_p1) + $signed(sext_ln326_57_fu_3524_p1));

assign add_ln326_27_fu_3611_p2 = ($signed(sext_ln326_59_fu_3608_p1) + $signed(sext_ln326_56_fu_3605_p1));

assign add_ln326_31_fu_3542_p2 = ($signed(sext_ln326_62_fu_3539_p1) + $signed(sext_ln326_61_fu_3536_p1));

assign add_ln326_35_fu_3557_p2 = ($signed(sext_ln326_66_fu_3554_p1) + $signed(sext_ln326_64_fu_3548_p1));

assign add_ln326_36_fu_3627_p2 = ($signed(sext_ln326_67_fu_3624_p1) + $signed(sext_ln326_63_fu_3621_p1));

assign add_ln326_37_fu_3637_p2 = ($signed(sext_ln326_68_fu_3633_p1) + $signed(sext_ln326_60_fu_3617_p1));

assign add_ln326_38_fu_3647_p2 = ($signed(sext_ln326_69_fu_3643_p1) + $signed(sext_ln326_53_fu_3601_p1));

assign add_ln326_3_fu_3470_p2 = ($signed(sext_ln326_40_fu_3467_p1) + $signed(sext_ln326_39_fu_3464_p1));

assign add_ln326_7_fu_3482_p2 = ($signed(sext_ln326_43_fu_3479_p1) + $signed(sext_ln326_42_fu_3476_p1));

assign add_ln326_8_fu_3569_p2 = ($signed(sext_ln326_44_fu_3566_p1) + $signed(sext_ln326_41_fu_3563_p1));

assign add_ln329_fu_915_p2 = (group_fu_506 + 32'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_block_state3_pp0_stage0_iter2));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((icmp_ln301_reg_4377 == 1'd1) & (layer6_out_x4_empty_n == 1'b0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign empty_fu_903_p2 = ((trunc_ln295_fu_893_p1 == 7'd1) ? 1'b1 : 1'b0);

assign group_3_fu_921_p3 = ((icmp_ln329_fu_909_p2[0:0] == 1'b1) ? 32'd0 : add_ln329_fu_915_p2);

assign icmp_ln299_fu_881_p2 = ((step_fu_510 == 7'd124) ? 1'b1 : 1'b0);

assign icmp_ln301_fu_897_p2 = ((group_fu_506 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln329_fu_909_p2 = ((group_fu_506 == 32'd1) ? 1'b1 : 1'b0);

assign input_word_158_fu_943_p1 = layer6_out_x4_dout[9:0];

assign lane_weight_10_fu_2597_p4 = {{w9_ravel_packed_q0[65:60]}};

assign lane_weight_13_fu_2662_p4 = {{w9_ravel_packed_q0[83:78]}};

assign lane_weight_15_fu_2710_p4 = {{w9_ravel_packed_q0[95:90]}};

assign lane_weight_18_fu_2775_p4 = {{w9_ravel_packed_q0[113:108]}};

assign lane_weight_20_fu_2823_p4 = {{w9_ravel_packed_q0[125:120]}};

assign lane_weight_23_fu_2888_p4 = {{w9_ravel_packed_q0[143:138]}};

assign lane_weight_25_fu_2936_p4 = {{w9_ravel_packed_q0[155:150]}};

assign lane_weight_28_fu_3001_p4 = {{w9_ravel_packed_q0[173:168]}};

assign lane_weight_30_fu_3049_p4 = {{w9_ravel_packed_q0[185:180]}};

assign lane_weight_33_fu_3114_p4 = {{w9_ravel_packed_q0[203:198]}};

assign lane_weight_35_fu_3162_p4 = {{w9_ravel_packed_q0[215:210]}};

assign lane_weight_38_fu_3227_p4 = {{w9_ravel_packed_q0[233:228]}};

assign lane_weight_3_fu_2436_p4 = {{w9_ravel_packed_q0[23:18]}};

assign lane_weight_5_fu_2484_p4 = {{w9_ravel_packed_q0[35:30]}};

assign lane_weight_8_fu_2549_p4 = {{w9_ravel_packed_q0[53:48]}};

assign lane_weight_fu_2377_p1 = w9_ravel_packed_q0[5:0];

assign sext_ln326_39_fu_3464_p1 = add_ln326_reg_4750;

assign sext_ln326_40_fu_3467_p1 = grp_fu_3801_p3;

assign sext_ln326_41_fu_3563_p1 = $signed(add_ln326_3_reg_4830);

assign sext_ln326_42_fu_3476_p1 = add_ln326_4_reg_4760;

assign sext_ln326_43_fu_3479_p1 = grp_fu_3809_p3;

assign sext_ln326_44_fu_3566_p1 = $signed(add_ln326_7_reg_4835);

assign sext_ln326_45_fu_3575_p1 = $signed(add_ln326_8_fu_3569_p2);

assign sext_ln326_46_fu_3488_p1 = add_ln326_9_reg_4770;

assign sext_ln326_47_fu_3491_p1 = grp_fu_3817_p3;

assign sext_ln326_48_fu_3579_p1 = $signed(add_ln326_12_reg_4840);

assign sext_ln326_49_fu_3500_p1 = add_ln326_13_reg_4780;

assign sext_ln326_50_fu_3503_p1 = grp_fu_3825_p3;

assign sext_ln326_51_fu_3582_p1 = $signed(add_ln326_16_reg_4845);

assign sext_ln326_52_fu_3591_p1 = $signed(add_ln326_17_fu_3585_p2);

assign sext_ln326_53_fu_3601_p1 = $signed(add_ln326_18_fu_3595_p2);

assign sext_ln326_54_fu_3512_p1 = add_ln326_19_reg_4790;

assign sext_ln326_55_fu_3515_p1 = grp_fu_3833_p3;

assign sext_ln326_56_fu_3605_p1 = $signed(add_ln326_22_reg_4850);

assign sext_ln326_57_fu_3524_p1 = add_ln326_23_reg_4800;

assign sext_ln326_58_fu_3527_p1 = grp_fu_3841_p3;

assign sext_ln326_59_fu_3608_p1 = $signed(add_ln326_26_reg_4855);

assign sext_ln326_60_fu_3617_p1 = $signed(add_ln326_27_fu_3611_p2);

assign sext_ln326_61_fu_3536_p1 = add_ln326_28_reg_4810;

assign sext_ln326_62_fu_3539_p1 = grp_fu_3849_p3;

assign sext_ln326_63_fu_3621_p1 = $signed(add_ln326_31_reg_4860);

assign sext_ln326_64_fu_3548_p1 = add_ln326_32_reg_4820;

assign sext_ln326_66_fu_3554_p1 = grp_fu_3857_p3;

assign sext_ln326_67_fu_3624_p1 = $signed(add_ln326_35_reg_4865);

assign sext_ln326_68_fu_3633_p1 = $signed(add_ln326_36_fu_3627_p2);

assign sext_ln326_69_fu_3643_p1 = $signed(add_ln326_37_fu_3637_p2);

assign sext_ln326_70_fu_3656_p1 = $signed(add_ln326_38_reg_4870);

assign trunc_ln295_fu_893_p1 = group_fu_506[6:0];

assign w9_ravel_packed_address0 = zext_ln299_fu_939_p1;

assign zext_ln299_fu_939_p1 = step_1_reg_4368;

endmodule //cnn_core_dense_wide_stream_array_array_ap_fixed_1u_config9_Pipeline_DenseValues
