// ==============================================================
// Generated by Vitis HLS v2023.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="cnn_core_cnn_core,hls_ip_2023_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=3.445000,HLS_SYN_LAT=140,HLS_SYN_TPT=135,HLS_SYN_MEM=7,HLS_SYN_DSP=0,HLS_SYN_FF=9751,HLS_SYN_LUT=23489,HLS_VERSION=2023_2}" *)

module cnn_core (
        waveform_TDATA,
        layer9_out_TDATA,
        ap_clk,
        ap_rst_n,
        waveform_TVALID,
        waveform_TREADY,
        ap_start,
        layer9_out_TVALID,
        layer9_out_TREADY,
        ap_done,
        ap_ready,
        ap_idle
);


input  [127:0] waveform_TDATA;
output  [31:0] layer9_out_TDATA;
input   ap_clk;
input   ap_rst_n;
input   waveform_TVALID;
output   waveform_TREADY;
input   ap_start;
output   layer9_out_TVALID;
input   layer9_out_TREADY;
output   ap_done;
output   ap_ready;
output   ap_idle;

 reg    ap_rst_n_inv;
wire    first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_start;
wire    first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_done;
wire    first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_continue;
wire    first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_idle;
wire    first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_ready;
wire   [1279:0] first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_layer4_out_x4_din;
wire    first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_layer4_out_x4_write;
wire    first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_waveform_TREADY;
wire    relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_start;
wire    relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_done;
wire    relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_continue;
wire    relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_idle;
wire    relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_ready;
wire    relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer4_out_x4_read;
wire   [1199:0] relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer5_out_x4_din;
wire    relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer5_out_x4_write;
reg    ap_sync_reg_relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_start;
wire    maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_start;
wire    maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_done;
wire    maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_continue;
wire    maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_idle;
wire    maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_ready;
wire    maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer5_out_x4_read;
wire   [799:0] maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer6_out_x4_din;
wire    maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer6_out_x4_write;
reg    ap_sync_reg_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_start;
wire    dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_start;
wire    dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_done;
wire    dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_continue;
wire    dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_idle;
wire    dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_ready;
wire    dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer6_out_x4_read;
wire   [31:0] dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer9_out_TDATA;
wire    dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer9_out_TVALID;
reg    ap_sync_reg_dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_start;
wire    layer4_out_x4_full_n;
wire   [1279:0] layer4_out_x4_dout;
wire   [2:0] layer4_out_x4_num_data_valid;
wire   [2:0] layer4_out_x4_fifo_cap;
wire    layer4_out_x4_empty_n;
wire    layer5_out_x4_full_n;
wire   [1199:0] layer5_out_x4_dout;
wire   [2:0] layer5_out_x4_num_data_valid;
wire   [2:0] layer5_out_x4_fifo_cap;
wire    layer5_out_x4_empty_n;
wire    layer6_out_x4_full_n;
wire   [799:0] layer6_out_x4_dout;
wire   [2:0] layer6_out_x4_num_data_valid;
wire   [2:0] layer6_out_x4_fifo_cap;
wire    layer6_out_x4_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_start = 1'b0;
#0 ap_sync_reg_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_start = 1'b0;
#0 ap_sync_reg_dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_start = 1'b0;
end

cnn_core_first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_s first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_start),
    .ap_done(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_done),
    .ap_continue(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_continue),
    .ap_idle(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_idle),
    .ap_ready(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_ready),
    .waveform_TVALID(waveform_TVALID),
    .layer4_out_x4_din(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_layer4_out_x4_din),
    .layer4_out_x4_num_data_valid(layer4_out_x4_num_data_valid),
    .layer4_out_x4_fifo_cap(layer4_out_x4_fifo_cap),
    .layer4_out_x4_full_n(layer4_out_x4_full_n),
    .layer4_out_x4_write(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_layer4_out_x4_write),
    .waveform_TDATA(waveform_TDATA),
    .waveform_TREADY(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_waveform_TREADY)
);

cnn_core_relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_s relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_start),
    .ap_done(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_done),
    .ap_continue(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_continue),
    .ap_idle(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_idle),
    .ap_ready(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_ready),
    .layer4_out_x4_dout(layer4_out_x4_dout),
    .layer4_out_x4_num_data_valid(layer4_out_x4_num_data_valid),
    .layer4_out_x4_fifo_cap(layer4_out_x4_fifo_cap),
    .layer4_out_x4_empty_n(layer4_out_x4_empty_n),
    .layer4_out_x4_read(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer4_out_x4_read),
    .layer5_out_x4_din(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer5_out_x4_din),
    .layer5_out_x4_num_data_valid(layer5_out_x4_num_data_valid),
    .layer5_out_x4_fifo_cap(layer5_out_x4_fifo_cap),
    .layer5_out_x4_full_n(layer5_out_x4_full_n),
    .layer5_out_x4_write(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer5_out_x4_write)
);

cnn_core_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_s maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_start),
    .ap_done(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_done),
    .ap_continue(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_continue),
    .ap_idle(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_idle),
    .ap_ready(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_ready),
    .layer5_out_x4_dout(layer5_out_x4_dout),
    .layer5_out_x4_num_data_valid(layer5_out_x4_num_data_valid),
    .layer5_out_x4_fifo_cap(layer5_out_x4_fifo_cap),
    .layer5_out_x4_empty_n(layer5_out_x4_empty_n),
    .layer5_out_x4_read(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer5_out_x4_read),
    .layer6_out_x4_din(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer6_out_x4_din),
    .layer6_out_x4_num_data_valid(layer6_out_x4_num_data_valid),
    .layer6_out_x4_fifo_cap(layer6_out_x4_fifo_cap),
    .layer6_out_x4_full_n(layer6_out_x4_full_n),
    .layer6_out_x4_write(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer6_out_x4_write)
);

cnn_core_dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_s dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_start),
    .ap_done(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_done),
    .ap_continue(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_continue),
    .ap_idle(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_idle),
    .ap_ready(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_ready),
    .layer6_out_x4_dout(layer6_out_x4_dout),
    .layer6_out_x4_num_data_valid(layer6_out_x4_num_data_valid),
    .layer6_out_x4_fifo_cap(layer6_out_x4_fifo_cap),
    .layer6_out_x4_empty_n(layer6_out_x4_empty_n),
    .layer6_out_x4_read(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer6_out_x4_read),
    .layer9_out_TDATA(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer9_out_TDATA),
    .layer9_out_TVALID(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer9_out_TVALID),
    .layer9_out_TREADY(layer9_out_TREADY)
);

cnn_core_fifo_w1280_d4_S layer4_out_x4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_layer4_out_x4_din),
    .if_full_n(layer4_out_x4_full_n),
    .if_write(first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_layer4_out_x4_write),
    .if_dout(layer4_out_x4_dout),
    .if_num_data_valid(layer4_out_x4_num_data_valid),
    .if_fifo_cap(layer4_out_x4_fifo_cap),
    .if_empty_n(layer4_out_x4_empty_n),
    .if_read(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer4_out_x4_read)
);

cnn_core_fifo_w1200_d4_S layer5_out_x4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer5_out_x4_din),
    .if_full_n(layer5_out_x4_full_n),
    .if_write(relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_layer5_out_x4_write),
    .if_dout(layer5_out_x4_dout),
    .if_num_data_valid(layer5_out_x4_num_data_valid),
    .if_fifo_cap(layer5_out_x4_fifo_cap),
    .if_empty_n(layer5_out_x4_empty_n),
    .if_read(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer5_out_x4_read)
);

cnn_core_fifo_w800_d4_S layer6_out_x4_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer6_out_x4_din),
    .if_full_n(layer6_out_x4_full_n),
    .if_write(maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_layer6_out_x4_write),
    .if_dout(layer6_out_x4_dout),
    .if_num_data_valid(layer6_out_x4_num_data_valid),
    .if_fifo_cap(layer6_out_x4_fifo_cap),
    .if_empty_n(layer6_out_x4_empty_n),
    .if_read(dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer6_out_x4_read)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_start <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_start <= 1'b0;
    end else begin
        if ((ap_start == 1'b1)) begin
            ap_sync_reg_relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_start <= 1'b1;
        end
    end
end

assign ap_done = dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_done;

assign ap_idle = (relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_idle & maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_idle & first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_idle & dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_idle);

assign ap_ready = first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_continue = 1'b1;

assign dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_start = (ap_sync_reg_dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_ap_start | ap_start);

assign first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_continue = 1'b1;

assign first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_ap_start = ap_start;

assign layer9_out_TDATA = dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer9_out_TDATA;

assign layer9_out_TVALID = dense_wide_stream_array_array_ap_fixed_24_14_5_3_0_1u_config9_U0_layer9_out_TVALID;

assign maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_continue = 1'b1;

assign maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_start = (ap_sync_reg_maxpool2d_wide_nonoverlap_cl_array_array_ap_fixed_80u_config6_U0_ap_start | ap_start);

assign relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_continue = 1'b1;

assign relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_start = (ap_sync_reg_relu_array_ap_fixed_80u_array_ap_ufixed_15_5_5_3_0_80u_relu_config5_U0_ap_start | ap_start);

assign waveform_TREADY = first_conv_2row_4lane_temporal_wide_cl_array_array_ap_fixed_80u_config4_U0_waveform_TREADY;

endmodule //cnn_core
